'use strict';
const crypto=require('node:crypto');
const VERSION='2026-09-07-identity-v1';
const norm=s=>String(s||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/&/g,' and ').replace(/[’']/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const unique=a=>[...new Set(a.filter(Boolean))];
const SELF_EMAILS=new Set(['justdeedeemusic@gmail.com']);
const emails=s=>unique((String(s||'').match(/[A-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)||[]).map(x=>x.toLowerCase()).filter(x=>!SELF_EMAILS.has(x)&&!x.endsWith('@facebook.com')&&!x.endsWith('@txt.voice.google.com')));
function phones(s){return unique((String(s||'').match(/(?<!\d)(?:\+?1[ .-]*)?\(?[2-9]\d{2}\)?[ .-]*[2-9]\d{2}[ .-]*\d{4}(?!\d)/g)||[]).map(x=>x.replace(/\D/g,'').replace(/^1(?=\d{10}$)/,'')));}
const SHARED=new Set(['gmail.com','googlemail.com','google.com','yahoo.com','outlook.com','hotmail.com','live.com','icloud.com','aol.com','msn.com','facebook.com','instagram.com','youtube.com','yelp.com','wixsite.com','square.site','godaddysites.com','sites.google.com','justdeedeemusic.com','mailchimp.com','constantcontact.com','eventbrite.com','ticketmaster.com','bandsintown.com','linktr.ee']);
function domain(s){try{const h=new URL(/^https?:\/\//i.test(s)?s:'https://'+s).hostname.toLowerCase().replace(/^www\./,'');return h.includes('.')&&![...SHARED].some(d=>h===d||h.endsWith('.'+d))?h:'';}catch{return '';}}
function socialProfile(raw,platform){let value=String(raw||'').trim();if(platform==='instagram'&&/^@?[\w.]+$/.test(value))value='https://instagram.com/'+value.replace(/^@/,'');try{const u=new URL(/^https?:\/\//i.test(value)?value:'https://'+value),host=u.hostname.toLowerCase().replace(/^www\./,'').replace(/^m\.(?=facebook\.com$)/,''),path=u.pathname.split('/').filter(Boolean);if(host==='instagram.com'&&path.length===1&&!['p','reel','reels','stories','direct','accounts','explore'].includes(path[0].toLowerCase()))return 'instagram:'+path[0].toLowerCase();if(['facebook.com','fb.com','m.me'].includes(host)){if(path[0]==='profile.php'&&/^\d+$/.test(u.searchParams.get('id')||''))return 'facebook:id:'+u.searchParams.get('id');if(path[0]==='people'&&path.length===3&&/^\d+$/.test(path[2]))return 'facebook:id:'+path[2];if(path.length===1&&!['photo','photo.php','photos','posts','reel','reels','watch','events','groups','share','sharer.php','login','help','pages','messages','me'].includes(path[0].toLowerCase()))return /^\d+$/.test(path[0])?'facebook:id:'+path[0]:'facebook:'+path[0].toLowerCase();}}catch{}return '';}
function freshText(text){return String(text||'').split(/\n\s*(?:On .{1,160}wrote:|_{5,}|-{2,}\s*(?:Original|Forwarded) message|Begin forwarded message:)/i)[0].split('\n').filter(l=>!/^\s*>/.test(l)).join('\n').slice(0,18000);}
function socialEvidence(c,messages=[]){const incoming=messages.filter(m=>m.from?.id===c.psid);const text=incoming.map(m=>freshText(m.message)).join('\n').slice(-40000);const profile=c.platform==='instagram'&&c.username?socialProfile('@'+c.username,'instagram'):socialProfile(c.profileUrl||'');return {source:c.platform||'messenger',identities:c.psid?[`${c.platform||'messenger'}:${c.accountId||'104617019336673'}:${c.psid}`]:[],names:[norm(c.name)].filter(n=>n.split(' ').length>=2),profiles:[profile].filter(Boolean),emails:[],phones:[],domains:[],subjects:[],text,claimedEmails:emails((text.match(/(?:my|our|booking|contact)\s+(?:e-?mail|email address)\s*(?:is|:)[^\n]{0,100}|(?:email|e-mail|contact|reach)\s+(?:me|us)\s+(?:at|on)[^\n]{0,100}/gi)||[]).join('\n')),claimedPhones:phones((text.match(/(?:my|our|booking|contact)\s+(?:phone|number)\s*(?:is|:)[^\n]{0,100}|(?:call|text|reach)\s+(?:me|us)\s+(?:at|on)[^\n]{0,100}/gi)||[]).join('\n'))};}
function voiceEvidence(c){return {source:'voice',identities:phones(c.phone).map(p=>'phone:'+p),phones:phones(c.phone),emails:[],profiles:[],names:[],domains:[],subjects:[],text:''};}
function resolve(index,evidence={},memory=[]){
 const es=new Set(evidence.emails||[]),ps=new Set(evidence.phones||[]),profiles=new Set(evidence.profiles||[]),domains=new Set(evidence.domains||[]),names=new Set(evidence.names||[]),text=' '+norm(evidence.text)+' ';
 const calendar=require('./calendarVenueMatching');const calendarIds=new Set((evidence.calendarEvents||[]).map(e=>calendar.matchEvent(index.map(v=>v.calendarRow||{'Place ID':v.id,'Place Name':v.name,Address:v.address||''}),e).venue?.['Place ID']).filter(Boolean));
 const named=index.filter(v=>(v.contactNames||[]).some(n=>n.split(' ').length>=2&&names.has(n)));
 const memoryIds=unique(memory.flatMap(m=>m.venueIds||[]));let blocked=memory.some(m=>m.blocked)||(memoryIds.some(id=>!index.some(v=>v.id===id&&v.linkable!==false)));
 const matches=index.map(v=>{const hard=[],soft=[];if(calendarIds.has(v.id))hard.push('authenticated calendar event with matching venue and location');if(memoryIds.includes(v.id))hard.push('previously confirmed sender identity');if(v.emails?.some(x=>es.has(x)))hard.push('exact saved email');if(v.phones?.some(x=>ps.has(x)))hard.push('exact saved phone');if(v.socialProfiles?.some(x=>profiles.has(x)))hard.push('exact saved social profile');if(v.domains?.some(x=>domains.has(x)))soft.push('business domain');if(v.names?.some(n=>n.length>=8&&n.split(' ').length>=2&&(evidence.subjects||[]).some(s=>(' '+s+' ').includes(' '+n+' '))))soft.push('venue name in subject');
 if(v.names?.some(n=>names.has(n)))soft.push('sender display name matches venue name');
 const contact=named.includes(v),mention=v.names?.some(n=>n.length>=8&&n.split(' ').length>=2&&text.includes(' '+n+' '));if(contact)soft.push('saved full contact name');if(mention)soft.push('venue mentioned in incoming text');
 const claimed=(v.emails||[]).some(e=>(evidence.claimedEmails||[]).includes(e))||(v.phones||[]).some(p=>(evidence.claimedPhones||[]).includes(p));if(claimed)soft.push('contact method stated in incoming text');
 // A saved full name needs separate corroboration; a name/venue mention alone is only a suggestion.
 if(contact&&named.length===1&&(mention||claimed)&&!evidence.testConversation)hard.push('unique saved full contact name with corroboration');
 return {v,hard,soft};}).filter(x=>x.hard.length||x.soft.length);
 const strong=matches.filter(x=>x.hard.length),weak=matches.filter(x=>x.soft.includes('business domain'));const chosen=strong.length?strong:weak;
 if(memoryIds.length>1)blocked=true;
 const one=!blocked&&chosen.length===1&&chosen[0].v.linkable!==false&&chosen[0].v.autoLinkable!==false;
 const ranked=matches.sort((a,b)=>b.hard.length-a.hard.length||b.soft.length-a.soft.length||a.v.name.localeCompare(b.v.name));
 const reason=one?'Unique match: '+[...chosen[0].hard,...chosen[0].soft].join(', ')+'.':blocked?'Confirmed identity has conflicting or unavailable venues; review the link.':chosen.some(x=>x.v.autoLinkable===false)?'Saved contact groups could not be read; review the venue in the app.':chosen.some(x=>x.v.linkable===false)?'Matching venue has a duplicate Place ID; review the spreadsheet.':chosen.length>1?'Multiple venues match this identity; choose the correct place.':matches.length?'Possible matches need confirmation; sender identity is not established.':'No reliable saved venue match. Use Link venue to search.';
 return {venue:one?chosen[0].v:null,candidates:ranked.map(x=>x.v),reason,version:VERSION,confidence:one?(strong.length?'exact-or-corroborated':'unique-directory-evidence'):'review'};
}
function createMemory(db){db=require('./operationStore').operationDb(db);const hash=s=>crypto.createHash('sha256').update(s).digest('hex');return {
 lookup:async keys=>Promise.all(unique(keys||[]).slice(0,20).map(async key=>{const d=db.__jddmOperationDb?(await require('./operationStore').memoCollection(db,'jddmVenueIdentities')).docs.find(d=>d.id===hash(key))?.data():(await db.doc('jddmVenueIdentities/'+hash(key)).get()).data();const values=Object.values(d?.assignments||{});return {venueIds:unique(values.filter(Boolean)),blocked:values.includes('')};})),
 remember:async(keys,source,venueId)=>{const assignment=hash(source);for(const key of unique(keys||[]).slice(0,20))await db.runTransaction(async tx=>{const ref=db.doc('jddmVenueIdentities/'+hash(key)),old=(await tx.get(ref)).data();tx.set(ref,{identity:key,assignments:{...old?.assignments,[assignment]:venueId||''},updatedAt:new Date().toISOString()});});}
};}
module.exports={VERSION,norm,emails,phones,domain,socialProfile,freshText,socialEvidence,voiceEvidence,resolve,createMemory};
