import test from 'node:test';import assert from 'node:assert/strict';
import {calculateMetrics,renderMetrics} from '../scripts/lib/dailySummaryMetrics.mjs';
import {isDue,generateSummary,validateSummary,renderSummary,recentMessages} from '../scripts/jddm-ai-daily-summary.mjs';
import {notificationBody} from '../functions/discordNotifications.js';
test('only scheduled daily alerts ping; copied source mentions never ping',()=>{const a=notificationBody('hello @everyone <@123> @here',{alert:true,part:0});assert.equal((a.content.match(/@everyone/g)||[]).length,1);assert.deepEqual(a.allowed_mentions.parse,['everyone']);assert.deepEqual(notificationBody('normal',{alert:false}).allowed_mentions.parse,[]);assert.deepEqual(notificationBody('part two',{alert:true,part:1}).allowed_mentions.parse,[]);});
test('8:05 Eastern gate accounts for DST and never starts early',()=>{assert.equal(isDue(new Date('2026-09-07T12:04:59Z')),false);assert.equal(isDue(new Date('2026-09-07T12:05:00Z')),true);assert.equal(isDue(new Date('2026-12-07T13:04:59Z')),false);assert.equal(isDue(new Date('2026-12-07T13:05:00Z')),true);});
test('metrics deduplicate gigs, separate conversations, use Mon-Sun dates and exclude closed followups',()=>{const rows=[{'Place Name':'Venue A','Place ID':'id1','Future Gigs':'2026-09-08; 2026-09-08; 2026-09-13','Next Follow Up':'2026-09-09',Status:'Contacted - Waiting on Reply'},{'Place Name':'Venue A','Place ID':'id1','Future Gigs':'2026-09-08'},{'Place Name':'Venue B','Future Gigs':'2026-09-14; 2026-02-30','Next Follow Up':'2026-09-10',Status:'Told No / Closed / No Music'},{'Place Name':'Venue C','Next Follow Up':'2026-09-06',Status:'Needs Review'}];const conversations=[{status:'deedee'},{status:'venue'},{status:'followup',followUpDate:'2026-09-13'},{status:'followup',followUpDate:'2026-09-14'}];const m=calculateMetrics({rows,conversations,today:'2026-09-07'});assert.equal(m.totalBookedGigs,3);assert.equal(m.bookedLocations,2);assert.equal(m.totalVenueLocations,3);assert.equal(m.gigsThisWeek,2);assert.equal(m.followUpPlacesThisWeek,1);assert.equal(m.followUpEmailsThisWeek,1);assert.equal(m.overduePlaces,1);assert.equal(m.waitingOnDeeDee,1);assert.equal(m.newRecordedGigs,null);assert.equal(m.lastBookedDate,'2026-09-14');assert.match(renderMetrics(m),/tracking starts/);const next=calculateMetrics({rows,conversations,today:'2026-09-07',previousGigKeys:m.gigKeys.slice(1)});assert.equal(next.newRecordedGigs,1);});
test('AI generation uses loopback only, with no cloud fallback and constrained references',async()=>{const input={sources:[{id:'S1',text:'Venue A needs reply',url:'https://discord.com/'}],warnings:[]};let calls=0;const result=await generateSummary(input,{fetchImpl:async(url,req)=>{calls++;assert.equal(url,'http://127.0.0.1:11434/api/chat');assert.equal(JSON.parse(req.body).think,false);return {ok:true,json:async()=>({message:{content:JSON.stringify({bullets:[{text:'Reply to Venue A.',sources:['S1']}]})}})};}});assert.equal(calls,1);assert.equal(result.bullets.length,1);await assert.rejects(generateSummary(input,{fetchImpl:async()=>{throw Error('offline');}}),/offline/);assert.throws(()=>validateSummary({bullets:[{text:'bad',sources:['invented']}]},input),/unsupported/);});
test('recap rendering removes model mentions and arbitrary URLs; recent-source filter excludes stale posts',()=>{const input={today:'2026-09-07',sources:[{id:'S1',url:'https://discord.com/channels/1/2'}],warnings:['Calendar unavailable.']};const out=renderSummary({bullets:[{text:'@everyone check https://evil.example (S1)',sources:['S1']}]},input);assert.ok(!out.includes('@everyone'));assert.ok(!out.includes('evil.example'));assert.ok(!out.includes('(S1)'));assert.match(out,/Calendar unavailable/);assert.equal(recentMessages([{type:0,timestamp:'2026-09-05',content:'Old'},{type:0,timestamp:'2026-09-07T10:00:00Z',content:'New booking'},{type:0,timestamp:'2026-09-07T10:00:00Z',content:'HOLD - JDDM calendar monitor TEST changed'}],new Date('2026-09-07T12:00:00Z')).length,1);});
