const test=require('node:test'),assert=require('node:assert/strict');
const m=require('../functions/calendarMonitor');
const event={id:'gig',title:'Test gig',location:'Test venue',start:'2026-09-10T22:00:00.000Z',end:'2026-09-11T00:00:00.000Z',details:'a',color:'',allDay:false};
const snapshot=(events,stamp='2026-09-07T09:00:00.000Z')=>m.validate({version:1,capturedAt:stamp,end:'2028-09-07T00:00:00.000Z',calendars:m.CALENDARS.map((id,i)=>({id,name:id,events:i?[]:events}))});
function fakeDb(){let data={};return {doc:()=>({get:async()=>({data:()=>structuredClone(data)}),set:async(v)=>{data={...data,...structuredClone(v)}}}),runTransaction:async fn=>fn({get:async()=>({data:()=>structuredClone(data)}),set:(_,v)=>{data={...data,...structuredClone(v)}}}),read:()=>data};}
test('baseline and unchanged checks stay quiet; metadata order does not matter',()=>{const s=snapshot([event]);assert.equal(m.changes(null,s).length,0);assert.equal(m.changes(s,snapshot([{...event}])).length,0);});
test('addition, time/title/location/description/color changes and cancellation',()=>{const s=snapshot([event]);assert.equal(m.changes(snapshot([]),s)[0].kind,'added');for(const [key,value] of Object.entries({title:'New',location:'Other',start:'2026-09-11T22:00:00Z',end:'2026-09-11T01:00:00Z',details:'b',color:'1',allDay:true})){const c=m.changes(s,snapshot([{...event,[key]:value}]))[0];assert.equal(c.kind,'changed',key);}assert.equal(m.changes(s,snapshot([]))[0].kind,'removed');});
test('Eastern summer/winter and all-day dates',()=>{assert.match(m.when(event),/6:00 PM EDT/);assert.match(m.when({...event,start:'2026-12-10T23:00:00Z',end:'2026-12-11T01:00:00Z'}),/6:00 PM EST/);assert.equal(m.when({...event,start:'2026-09-10T04:00:00Z',allDay:true}),'Sep 10, 2026 (all day)');});
test('recurring changes grouped once, not one post per occurrence',()=>{const events=[event,{...event,start:'2026-09-17T22:00:00Z',end:'2026-09-18T00:00:00Z'}];const c=m.changes(snapshot(events),snapshot(events.map(e=>({...e,title:'New series'}))));assert.equal(c.length,1);assert.match(m.message(c[0]),/Recurring series/);});
test('rolling future boundary does not create false new event notifications',()=>{const a=snapshot([]),b=snapshot([{...event,start:'2028-09-07T06:00:00Z',end:'2028-09-07T08:00:00Z'}]);b.end='2028-09-08T00:00:00Z';assert.deepEqual(m.changes(a,b),[]);});
test('partial or failed calendar reads cannot imply cancellations',()=>{const s=snapshot([event]);s.calendars.pop();assert.throws(()=>m.validate(s),/Invalid/);});
test('durable retry resumes after successful messages without repeating baseline',async()=>{const db=fakeDb(),sent=[];let fail=true;const run=m.createCalendarMonitor({db,discord:async(_m,_p,body)=>{if(sent.length===1&&fail){fail=false;throw Error('transient')}sent.push(body);}});await run(snapshot([]));const next=snapshot([event,{...event,id:'other'}],'2026-09-07T09:05:00Z');await assert.rejects(run(next));assert.equal(sent.length,1);assert.equal(db.read().next,1);await run(next);assert.equal(sent.length,2);assert.equal(db.read().pending,null);await run(snapshot(next.calendars[0].events,'2026-09-07T09:10:00Z'));assert.equal(sent.length,2);assert.deepEqual(sent[0].allowed_mentions,{parse:[]});assert.equal(sent[0].enforce_nonce,true);});
test('old snapshots cannot roll back new state',async()=>{const db=fakeDb();const run=m.createCalendarMonitor({db,discord:async()=>{throw Error('must not send')}});await run(snapshot([event],'2026-09-07T10:00:00Z'));assert.equal((await run(snapshot([]))).stale,true);assert.equal(m.unpack(db.read().baseline).calendars[0].events.length,1);});
test('signed endpoint rejects tampering and accepts intact payload',async()=>{const crypto=require('node:crypto'),body=JSON.stringify(snapshot([])),stamp=String(Date.now());let calls=0;const h=m.createHandler({secret:()=> 'test-key',run:async()=>{calls++;return {posted:0}}});const signature=crypto.createHmac('sha256','test-key').update(stamp+'.'+body).digest('hex');const response=()=>({code:200,status(c){this.code=c;return this},json(b){this.body=b;return this}});for(const [raw,status]of [[body,200],[body+' ',401]]){let r=response();await h({method:'POST',rawBody:Buffer.from(raw),get:n=>n==='x-jddm-timestamp'?stamp:signature},r);assert.equal(r.code,status);}assert.equal(calls,1);});
test('Apps Script uses ASCII wire encoding while preserving accents and emoji, and schedules hourly',()=>{
 const fs=require('fs'),vm=require('vm'),crypto=require('crypto');let wire,minutes,creates=0;const props=new Map([['JDDM_CALENDAR_MONITOR_KEY','test-key']]);
 const e={getId:()=> 'a',getTitle:()=> 'Café 🎶 — Déjà Vu',getLocation:()=> 'José’s place',getStartTime:()=>new Date(event.start),getEndTime:()=>new Date(event.end),isAllDayEvent:()=>false,getColor:()=>'',getDescription:()=> 'unicode notes'};
 const ctx={console:{log(){}},JDDM_CALENDAR_IDS:m.CALENDARS,Date,LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock(){}})},PropertiesService:{getScriptProperties:()=>({getProperty:k=>props.get(k),setProperty:(k,v)=>props.set(k,v)})},CalendarApp:{getCalendarById:id=>({getEvents:()=>[e],getName:()=>id})},Utilities:{DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(alg,s)=>[...crypto.createHash(alg).update(s).digest()],base64Encode:b=>Buffer.from(b).toString('base64'),computeHmacSha256Signature:(s,k)=>[...crypto.createHmac('sha256',k).update(s).digest()]},UrlFetchApp:{fetch:(_url,options)=>{wire=options;return {getResponseCode:()=>200,getContentText:()=>JSON.stringify({ok:true,posted:0})}}},ScriptApp:{getProjectTriggers:()=>creates?[{getHandlerFunction:()=> 'runJddmCalendarChangeMonitor'}]:[],newTrigger:name=>({timeBased:()=>({everyHours:n=>{minutes=n;return {create:()=>creates++}}})})}};
 vm.createContext(ctx);vm.runInContext(fs.readFileSync('google-apps-script/jddm-spreadsheet-bridge/CalendarMonitor.gs','utf8'),ctx);ctx.installJddmCalendarChangeMonitor();ctx.installJddmCalendarChangeMonitor();assert.equal(minutes,1);assert.equal(creates,1);assert.doesNotMatch(wire.payload,/[^\x00-\x7F]/);assert.equal(JSON.parse(wire.payload).calendars[0].events[0].title,e.getTitle());assert.equal(wire.headers['x-jddm-signature'],crypto.createHmac('sha256','test-key').update(wire.headers['x-jddm-timestamp']+'.'+wire.payload).digest('hex'));
});
