const {chromium,expect}=require('@playwright/test'),fs=require('fs'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({headless:true});try{
const page=await browser.newPage({viewport:{width:390,height:844}}),html=fs.readFileSync('index.html','utf8');await page.setContent(html.slice(html.indexOf('    <div id="venue-edit-modal"'),html.indexOf('    <div id="booking-email-modal"')));await page.addStyleTag({path:'styles.css'});
await page.evaluate(()=>{window.calls={create:[],save:[]};window.fail=0;window.delay=0;window.saved={};window.created={};const result=()=>({ok:true,rawFields:window.saved,venue:{'Place ID':'test'}});window.BARK={services:{spreadsheet:{isConfigured:()=>true,getVenue:async()=>result(),createVenue:async p=>{window.calls.create.push(p);if(window.created[p.requestId])return {...window.created[p.requestId],replayed:true};window.saved=p.rawFields;const r=result();window.created[p.requestId]=r;if(window.loseCreate){window.loseCreate=false;throw Error('Lost response');}return r;},saveVenue:async p=>{window.calls.save.push(p);if(window.delay)await new Promise(r=>setTimeout(r,window.delay));if(window.conflict){const e=Error('Changed in another window');e.code='VENUE_CONFLICT';throw e;}if(window.fail-->0)throw Error('Offline');window.saved={...window.saved,...p.rawFields};return result();}}}};});
for(const path of ['functions/contactRecords.js','modules/bookingSchema.js','modules/venueEditModal.js'])await page.addScriptTag({path});
const modal=page.locator('#venue-edit-modal'),card=n=>page.locator('[data-person-index]').nth(n),x=page.getByRole('button',{name:'Close editor',exact:true}),dialog=()=>page.locator('dialog[open]');const choice=name=>dialog().getByRole('button',{name,exact:true}).click();const open=()=>page.evaluate(()=>window.BARK.openVenueEditor({id:'test',name:'Test venue'}));
// Two partial people, one notes box each, and a confirmation before X saves.
await page.evaluate(()=>window.BARK.openNewVenueEditor());await page.locator('#venue-edit-source-place-name').fill('Partial contacts');await card(0).getByRole('textbox',{name:'Phone 1',exact:true}).fill('13305550123');await page.locator('[data-person-add]').click();await card(1).getByRole('textbox',{name:'Email 1',exact:true}).fill('person2@example.com');await card(1).locator('.venue-person-notes summary').click();await card(1).getByRole('textbox',{name:'Contact notes',exact:true}).fill('Phone not known yet');assert.equal(await page.locator('[data-contact-note]').count(),0);assert.equal(await page.locator('[data-person-notes]').count(),2);assert.equal(await page.evaluate(()=>window.dispatchEvent(new Event('beforeunload',{cancelable:true}))),false);await x.click();await expect(dialog()).toHaveAttribute('aria-label','Save changes before closing?');await choice('Keep editing');await expect(modal).toBeVisible();await x.click();await choice('Save and close');await expect(modal).toBeHidden();let data=await page.evaluate(()=>window.JDDMContacts.read(window.saved));assert.equal(data.contacts[0].phones[0].value,'(330) 555-0123');assert.equal(data.contacts[0].emails.length,0);assert.equal(data.contacts[1].notes,'Phone not known yet');assert.equal(data.contacts[1].phones.length,0);
// Removing a person or method requires confirmation; cancel leaves everything intact.
await open();await card(1).locator('[data-person-remove]').click();await choice('Keep contact');await expect(page.locator('[data-person-index]')).toHaveCount(2);await card(0).locator('[data-contact-add="phones"]').click();await card(0).getByRole('textbox',{name:'Phone 2',exact:true}).fill('4405550199');await card(0).locator('[data-contact-remove]').click();await choice('Keep it');await expect(card(0).getByRole('textbox',{name:'Phone 2',exact:true})).toHaveValue('(440) 555-0199');await card(0).locator('[data-contact-remove]').click();await choice('Remove method');await card(1).locator('[data-person-remove]').click();await choice('Remove contact');await expect(page.locator('[data-person-index]')).toHaveCount(1);await x.click();await choice('Discard changes');await expect(modal).toBeHidden();await open();await expect(page.locator('[data-person-index]')).toHaveCount(2);await x.click();await expect(modal).toBeHidden();
// Failed save offers retry/keep/discard and never silently drops the draft.
await open();await card(0).getByRole('textbox',{name:'Contact name',exact:true}).fill('Keep after error');await page.evaluate(()=>window.fail=1);await x.click();await choice('Save and close');await expect(dialog()).toHaveAttribute('aria-label','Changes are not saved');await choice('Keep editing');await expect(card(0).getByRole('textbox',{name:'Contact name',exact:true})).toHaveValue('Keep after error');await x.click();await choice('Save and close');await expect(modal).toBeHidden();
// Double X and Save+X share the same pending write.
await open();await card(0).getByRole('textbox',{name:'Contact name',exact:true}).fill('One save');let count=await page.evaluate(()=>{window.delay=200;return window.calls.save.length;});await page.evaluate(()=>{void window.BARK.closeVenueEditor();void window.BARK.closeVenueEditor();});await expect(page.locator('dialog[open]')).toHaveCount(1);await choice('Save and close');await expect(modal).toBeHidden();assert.equal(await page.evaluate(()=>window.calls.save.length),count+1);await open();await card(0).getByRole('textbox',{name:'Contact name',exact:true}).fill('Save then X');count=await page.evaluate(()=>window.calls.save.length);await page.locator('#venue-edit-save').click();await x.click();await expect(modal).toBeHidden();assert.equal(await page.evaluate(()=>window.calls.save.length),count+1);await page.evaluate(()=>window.delay=0);
// Escape and backdrop clicks warn before discarding; untouched new forms do not write.
await open();await card(0).getByRole('textbox',{name:'Contact name',exact:true}).fill('Escape draft');await page.keyboard.press('Escape');await choice('Keep editing');await page.locator('.venue-edit-backdrop').click({position:{x:2,y:2},force:true});await choice('Discard changes');await expect(modal).toBeHidden();count=await page.evaluate(()=>window.calls.create.length);await page.evaluate(()=>window.BARK.openNewVenueEditor());await x.click();await expect(modal).toBeHidden();assert.equal(await page.evaluate(()=>window.calls.create.length),count);
// Invalid email stays in the editor; failed new-place retry uses the same ID and keeps later notes.
await page.evaluate(()=>{window.loseCreate=true;return window.BARK.openNewVenueEditor();});await page.locator('#venue-edit-source-place-name').fill('Retry creation');await card(0).getByRole('textbox',{name:'Email 1',exact:true}).fill('unfinished@');await x.click();await choice('Save and close');await choice('Keep editing');await card(0).getByRole('textbox',{name:'Email 1',exact:true}).fill('valid@example.com');await x.click();await choice('Save and close');await choice('Keep editing');await page.locator('#venue-edit-source-notes').fill('Edited after lost response');await x.click();await choice('Save and close');await expect(modal).toBeHidden();const attempts=await page.evaluate(()=>window.calls.create.slice(-2));assert.equal(attempts[0].requestId,attempts[1].requestId);assert.equal(await page.evaluate(()=>window.saved.Notes),'Edited after lost response');
// Old per-method notes are consolidated with context and are editable only in the person's box.
await page.evaluate(()=>{window.saved={'Place Name':'Legacy','Contact Name':'Legacy person','Email/Contact':'a@example.com','Phone Number':'3305550123','Booking Contact':window.JDDMContacts.encode({version:2,contacts:[{...window.JDDMContacts.empty(),name:'Legacy person',notes:'Person note',emails:[{value:'a@example.com',note:'Email note'}],phones:[{value:'3305550123',note:'Phone note'}]}]})};});await open();await card(0).locator('.venue-person-notes summary').click();const note=card(0).getByRole('textbox',{name:'Contact notes',exact:true});await expect(note).toContainText('Email note');await expect(note).toContainText('Phone note');await note.fill('One edited note');await page.locator('#venue-edit-save').click();await expect(page.locator('#venue-edit-status')).toContainText('Saved');data=await page.evaluate(()=>window.JDDMContacts.read(window.saved));assert.equal(data.contacts[0].notes,'One edited note');assert(data.contacts[0].emails.every(i=>!i.note));await x.click();await expect(modal).toBeHidden();
// A conflict preserves the draft and reload requires explicit confirmation.
await open();await card(0).getByRole('textbox',{name:'Contact name',exact:true}).fill('Conflicting draft');await page.evaluate(()=>window.conflict=true);await page.locator('#venue-edit-save').click();await expect(page.locator('#venue-edit-status')).toContainText('another window');await page.locator('#venue-edit-refresh').click();await choice('Keep editing');await expect(card(0).getByRole('textbox',{name:'Contact name',exact:true})).toHaveValue('Conflicting draft');await page.evaluate(()=>window.conflict=false);await page.locator('#venue-edit-refresh').click();await choice('Reload latest');await expect(card(0).getByRole('textbox',{name:'Contact name',exact:true})).toHaveValue('Legacy person');await x.click();await expect(modal).toBeHidden();
console.log('PASS: one notes box, migration, fragmented contacts, removal confirmations, unsaved/failed-close warnings, keep/discard/save, double X, Save+X, backdrop, Escape, retries, conflict protection.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
