const {chromium,expect}=require('@playwright/test'),fs=require('fs'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({headless:true});try {
const page=await browser.newPage({viewport:{width:1000,height:950}});const html=fs.readFileSync('index.html','utf8');await page.setContent(html.slice(html.indexOf('    <div id="venue-edit-modal"'),html.indexOf('    <div id="booking-email-modal"')));await page.addStyleTag({path:'styles.css'});
await page.evaluate(()=>{
 window.calls={create:[],save:[],get:[]};window.failSaves=0;window.delaySave=0;window.createdRecords={};
 const result=()=>({ok:true,rawFields:window.saved,venue:{'Place ID':'test'}});
 window.BARK={services:{spreadsheet:{isConfigured:()=>true,
 getVenue:async id=>{window.calls.get.push(id);if(window.waitForLoad&&id==='slow')return new Promise(resolve=>window.finishSlow=()=>resolve({rawFields:{'Place Name':'Stale venue','Contact Name':'Stale'}}));return result();},
 createVenue:async ({rawFields,requestId})=>{window.calls.create.push({rawFields,requestId});if(window.createdRecords[requestId])return {...window.createdRecords[requestId],replayed:true};window.saved={...rawFields};const r=result();window.createdRecords[requestId]=r;if(window.loseCreateResponse){window.loseCreateResponse=false;throw Error('Connection interrupted');}return r;},
 saveVenue:async ({rawFields})=>{window.calls.save.push(rawFields);if(window.delaySave)await new Promise(r=>setTimeout(r,window.delaySave));if(window.failSaves-->0)throw Error('Offline test');window.saved={...window.saved,...rawFields};return result();}
 }}};
});for(const path of ['functions/contactRecords.js','modules/bookingSchema.js','modules/venueEditModal.js'])await page.addScriptTag({path});
const modal=page.locator('#venue-edit-modal'),x=page.getByRole('button',{name:'Close editor',exact:true}),card=n=>page.locator('[data-person-index]').nth(n);
const open=()=>page.evaluate(()=>window.BARK.openVenueEditor({id:'test',name:'Test venue'}));
// Fragmented, unnamed contacts and missing-method notes; X creates and saves.
await page.evaluate(()=>window.BARK.openNewVenueEditor());await page.locator('#venue-edit-source-place-name').fill('Fragmented contacts test');await card(0).getByRole('textbox',{name:'Phone 1',exact:true}).fill('13305550123');await card(0).getByRole('textbox',{name:'Phone 1',exact:true}).blur();await expect(card(0).getByRole('textbox',{name:'Phone 1',exact:true})).toHaveValue('(330) 555-0123');await page.locator('[data-person-add]').click();await card(1).getByRole('textbox',{name:'Email 1',exact:true}).fill('person2@example.com');await card(1).locator('[aria-label="Notes for phone 1"]').click();await card(1).locator('[data-contact-group="phones"] textarea').fill('Ask for their number later');await x.click();await expect(modal).toBeHidden();let data=await page.evaluate(()=>window.JDDMContacts.read(window.saved));assert.equal(data.contacts.length,2);assert.equal(data.contacts[0].name,'');assert.equal(data.contacts[0].emails.length,0);assert.equal(data.contacts[1].phones[0].value,'');assert.equal(data.contacts[1].phones[0].note,'Ask for their number later');assert.equal(data.contacts[1].emails[0].value,'person2@example.com');
// Opening/closing unchanged does not save or generate notifications.
await open();let count=await page.evaluate(()=>window.calls.save.length);await x.click();await expect(modal).toBeHidden();assert.equal(await page.evaluate(()=>window.calls.save.length),count);
// Close failures preserve the form; retry works with a note-only edit.
await open();await card(0).locator('.venue-person-notes summary').click();await card(0).getByRole('textbox',{name:'Contact notes',exact:true}).fill('Saved even when X is used');await page.evaluate(()=>window.failSaves=1);await x.click();await expect(modal).toBeVisible();await expect(page.locator('#venue-edit-status')).toContainText('Not saved yet');await expect(card(0).getByRole('textbox',{name:'Contact notes',exact:true})).toHaveValue('Saved even when X is used');await x.click();await expect(modal).toBeHidden();
// Two X requests during a slow save share exactly one write.
await open();await card(0).getByRole('textbox',{name:'Contact name',exact:true}).fill('Phone contact');count=await page.evaluate(()=>{window.delaySave=300;return window.calls.save.length;});await page.evaluate(()=>{window.BARK.closeVenueEditor();window.BARK.closeVenueEditor();});await expect(modal).toBeVisible();assert.equal(await page.locator('#venue-edit-source-fields').evaluate(e=>e.inert),true);await expect(modal).toBeHidden();assert.equal(await page.evaluate(()=>window.calls.save.length),count+1);
// Save followed immediately by X also makes one write.
await open();await card(1).getByRole('textbox',{name:'Contact name',exact:true}).fill('Email contact');count=await page.evaluate(()=>window.calls.save.length);await page.locator('#venue-edit-save').click();await x.click();await expect(modal).toBeHidden();assert.equal(await page.evaluate(()=>window.calls.save.length),count+1);await page.evaluate(()=>window.delaySave=0);
// Reload preserves unsaved edits, and Escape saves rather than discarding them.
await open();await card(0).getByRole('textbox',{name:'Contact name',exact:true}).fill('Preserve through Reload');count=await page.evaluate(()=>window.calls.save.length);await page.locator('#venue-edit-refresh').click();await expect(page.locator('#venue-edit-status')).toContainText('loaded');await expect(card(0).getByRole('textbox',{name:'Contact name',exact:true})).toHaveValue('Preserve through Reload');assert.equal(await page.evaluate(()=>window.calls.save.length),count+1);await card(0).getByRole('textbox',{name:'Contact name',exact:true}).fill('Save on Escape');await page.keyboard.press('Escape');await expect(modal).toBeHidden();assert.equal(await page.evaluate(()=>window.JDDMContacts.read(window.saved).contacts[0].name),'Save on Escape');
// Empty new form closes freely. An invalid email remains visible until corrected.
count=await page.evaluate(()=>window.calls.create.length);await page.evaluate(()=>window.BARK.openNewVenueEditor());await x.click();await expect(modal).toBeHidden();assert.equal(await page.evaluate(()=>window.calls.create.length),count);await page.evaluate(()=>window.BARK.openNewVenueEditor());await page.locator('#venue-edit-source-place-name').fill('Validation test');await card(0).getByRole('textbox',{name:'Email 1',exact:true}).fill('unfinished@');await x.click();await expect(modal).toBeVisible();await expect(page.locator('#venue-edit-status')).toContainText('highlighted');await card(0).getByRole('textbox',{name:'Email 1',exact:true}).fill('complete@example.com');await x.click();await expect(modal).toBeHidden();
// A lost create response and retry must not create a second venue or lose later edits.
await page.evaluate(()=>{window.loseCreateResponse=true;return window.BARK.openNewVenueEditor();});await page.locator('#venue-edit-source-place-name').fill('Interrupted creation');await x.click();await expect(page.locator('#venue-edit-status')).toContainText('Not saved yet');await page.locator('#venue-edit-source-notes').fill('Added after interrupted response');await x.click();await expect(modal).toBeHidden();const attempts=await page.evaluate(()=>window.calls.create.slice(-2));assert.equal(attempts[0].requestId,attempts[1].requestId);assert.equal(await page.evaluate(()=>window.saved.Notes),'Added after interrupted response');
// A response from a dismissed loading editor cannot replace the next venue.
await page.evaluate(()=>{window.waitForLoad=true;void window.BARK.openVenueEditor({id:'slow',name:'Slow venue'});});await expect(page.locator('#venue-edit-status')).toContainText('Loading');await x.click();await expect(modal).toBeHidden();await open();await page.evaluate(()=>window.finishSlow());await expect(card(0).getByRole('textbox',{name:'Contact name',exact:true})).not.toHaveValue('Stale');await x.click();await expect(modal).toBeHidden();
console.log('PASS: fragmented/unnamed contacts, placeholders, missing-method notes, US formatting, X autosave, no-op close, failures/retry, double X, Save+X, empty new form, invalid email, lost create response, stale loads.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
