#!/usr/bin/env python3
"""
Generate a standalone Google Apps Script project that installs the Ohio music
intel database tabs into the cloud master spreadsheet.

The generated Apps Script opens the master spreadsheet by ID, leaves Sheet1 in
place for the app feed, and replaces only the music-intel tabs.
"""

from __future__ import annotations

import argparse
import csv
import importlib.util
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
WORKBOOK_BUILDER = ROOT / "scripts/build-ohio-music-intel-workbook.py"
DEFAULT_PROJECT_DIR = ROOT / ".codex/ohio-music-intel-apps-script"
DEFAULT_CSV_DIR = ROOT / ".codex/ohio-music-intel-csv"
DEFAULT_SPREADSHEET_ID = "1UBuHO1MSwYTuSobheGFyt-b05HTxHVbKrr_u7M8q2Sw"
DEFAULT_XLSX = ROOT / "outputs/ohio_music_intel/JustDeeDeeMusic_Ohio_Music_Intel_Database.xlsx"

TAB_FILES = [
    ("Venues_DB", "venues.csv"),
    ("Artists_DB", "artists.csv"),
    ("Events_DB", "events.csv"),
    ("Event_Artists_DB", "event_artists.csv"),
    ("Venue_Artist_History_DB", "venue_artist_history.csv"),
    ("Review_Queue_DB", "review_queue.csv"),
    ("Raw_Scrape_Log_DB", "raw_scrape_log.csv"),
]

README_VALUES = [
    ["Just Dee Dee Music Ohio Music Intel Database", ""],
    ["Purpose", "Cloud storage tabs for venues, artists, gigs, repeat performers, and raw scrape evidence."],
    ["Important", "Sheet1 remains the live app venue feed. These _DB tabs sit beside it as the music intelligence database."],
    ["Scale", "A recurring venue creates more Events_DB rows. A multi-band night creates multiple Event_Artists_DB rows. Do not create one tab per artist or venue."],
    ["Main workflow", "Scrape or import raw rows, review matches in Review_Queue_DB, then promote clean records into Artists_DB / Events_DB / Event_Artists_DB."],
]

LOOKUP_VALUES = [
    ["lookup_type", "value", "meaning"],
    ["artist_type", "solo", "One primary performer"],
    ["artist_type", "duo", "Two-person act"],
    ["artist_type", "band", "Group act"],
    ["artist_type", "DJ", "DJ or electronic act"],
    ["artist_type", "open_mic_host", "Open mic host or recurring open mic identity"],
    ["artist_type", "tribute", "Tribute or cover concept"],
    ["artist_type", "other", "Use when the standard types do not fit"],
    ["artist_type", "unknown", "Needs review"],
    ["event_status", "new", "Fresh record from a source"],
    ["event_status", "needs_review", "Needs human confirmation"],
    ["event_status", "needs_confirmation", "Likely event but venue/date details may be incomplete"],
    ["event_status", "reviewed", "Human reviewed"],
    ["event_status", "confirmed", "Confirmed active gig"],
    ["event_status", "duplicate", "Duplicate of another event"],
    ["event_status", "ignore", "Not relevant"],
    ["event_status", "completed", "Past completed gig"],
]


def read_csv_values(path: Path) -> list[list[str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return [row for row in csv.reader(handle)]


def load_export_database():
    spec = importlib.util.spec_from_file_location("ohio_music_intel_workbook", WORKBOOK_BUILDER)
    if not spec or not spec.loader:
        raise RuntimeError(f"Could not load workbook builder from {WORKBOOK_BUILDER}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module.export_database


def build_project(project_dir: Path, csv_dir: Path, spreadsheet_id: str) -> dict[str, int]:
    export_database = load_export_database()
    counts = export_database(DEFAULT_XLSX, csv_dir)
    project_dir.mkdir(parents=True, exist_ok=True)

    tables: dict[str, list[list[str]]] = {
        "Music_Intel_README": README_VALUES,
        "Lookups_DB": LOOKUP_VALUES,
    }
    for tab_name, file_name in TAB_FILES:
        tables[tab_name] = read_csv_values(csv_dir / file_name)

    code = f"""/**
 * Generated by scripts/build-ohio-music-intel-apps-script.py.
 * Run installOhioMusicIntelDatabase() to write the DB tabs into the master sheet.
 */

var TARGET_SPREADSHEET_ID = {json.dumps(spreadsheet_id)};
var MUSIC_INTEL_TABLES = {json.dumps(tables, ensure_ascii=False)};

function installOhioMusicIntelDatabase() {{
  var ss = SpreadsheetApp.openById(TARGET_SPREADSHEET_ID);
  var installed = [];
  Object.keys(MUSIC_INTEL_TABLES).forEach(function(sheetName) {{
    var values = MUSIC_INTEL_TABLES[sheetName] || [[]];
    var sheet = ss.getSheetByName(sheetName);
    if (!sheet) sheet = ss.insertSheet(sheetName);
    sheet.clear();
    ensureSize_(sheet, values.length, values[0].length);
    sheet.getRange(1, 1, values.length, values[0].length).setValues(values);
    formatMusicIntelSheet_(sheet, values.length, values[0].length);
    installed.push({{ sheetName: sheetName, rows: values.length, columns: values[0].length }});
  }});
  ss.toast('Ohio Music Intel database tabs updated.', 'JDDM', 6);
  Logger.log(JSON.stringify({{ ok: true, spreadsheetId: TARGET_SPREADSHEET_ID, installed: installed }}, null, 2));
  return {{ ok: true, spreadsheetId: TARGET_SPREADSHEET_ID, installed: installed }};
}}

function ensureSize_(sheet, rows, columns) {{
  if (sheet.getMaxRows() < rows) sheet.insertRowsAfter(sheet.getMaxRows(), rows - sheet.getMaxRows());
  if (sheet.getMaxColumns() < columns) sheet.insertColumnsAfter(sheet.getMaxColumns(), columns - sheet.getMaxColumns());
}}

function formatMusicIntelSheet_(sheet, rowCount, columnCount) {{
  sheet.setFrozenRows(1);
  sheet.getRange(1, 1, 1, columnCount)
    .setFontWeight('bold')
    .setBackground('#134f5c')
    .setFontColor('#ffffff');
  if (rowCount > 1) {{
    sheet.getRange(1, 1, rowCount, columnCount).createFilter();
  }}
  var widths = {{
    Music_Intel_README: [280, 760],
    Venues_DB: [260, 220, 260, 160, 80, 80, 120, 120, 220, 140, 180, 240, 150, 240, 150, 110, 140, 160, 240, 150, 130, 130, 130, 180, 220, 180, 360],
    Artists_DB: [260, 240, 140, 150, 90, 190, 240, 280, 240, 150, 130, 130, 110, 180, 140, 360],
    Events_DB: [280, 120, 120, 120, 340, 260, 260, 160, 90, 180, 260, 360, 140, 140, 480, 200, 260, 180, 420, 360],
    Event_Artists_DB: [280, 280, 280, 260, 160, 120, 140, 140, 180],
    Venue_Artist_History_DB: [280, 260, 280, 260, 120, 120, 120, 280, 360],
    Review_Queue_DB: [280, 160, 110, 140, 280, 240, 240, 340, 120, 180, 360, 360, 440, 360],
    Raw_Scrape_Log_DB: [280, 180, 280, 340, 360, 120, 120, 240, 320, 160, 280, 200, 480, 240, 180, 480, 160, 120, 120],
    Lookups_DB: [160, 220, 520]
  }}[sheet.getName()] || [];
  for (var i = 0; i < columnCount; i++) {{
    sheet.setColumnWidth(i + 1, widths[i] || 180);
  }}
  sheet.autoResizeRows(1, Math.min(rowCount, 200));
}}
"""

    manifest = {
        "timeZone": "America/New_York",
        "exceptionLogging": "STACKDRIVER",
        "runtimeVersion": "V8",
        "oauthScopes": [
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/script.external_request",
        ],
    }

    (project_dir / "Code.js").write_text(code, encoding="utf-8")
    (project_dir / "appsscript.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return counts


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate the Ohio music intel Apps Script seeder project.")
    parser.add_argument("--project-dir", type=Path, default=DEFAULT_PROJECT_DIR)
    parser.add_argument("--csv-dir", type=Path, default=DEFAULT_CSV_DIR)
    parser.add_argument("--spreadsheet-id", default=DEFAULT_SPREADSHEET_ID)
    args = parser.parse_args()
    counts = build_project(args.project_dir, args.csv_dir, args.spreadsheet_id)
    print(json.dumps({"project_dir": str(args.project_dir), **counts}, indent=2))


if __name__ == "__main__":
    main()
