const test=require('node:test');const assert=require('node:assert/strict');
const {STATES,dateKey,validDate,plainBody,messageChunks,createConversationService,controls}=require('../discordConversations');
function message(id,body,from='venue@example.com',time=Date.now()){return {id,threadId:'gmail-thread',internalDate:String(time),labelIds:['INBOX'],payload:{mimeType:'text/plain',headers:[{name:'From',value:from},{name:'To',value:'justdeedeemusic@gmail.com'},{name:'Subject',value:'Re: Booking'}],body:{data:Buffer.from(body).toString('base64url')}}};}
function fakeDb(){const data=new Map();function ref(path){return {get:async()=>({exists:data.has(path),data:()=>structuredClone(data.get(path))}),set:async(value,options)=>{data.set(path,options?.merge?{...data.get(path),...structuredClone(value)}:structuredClone(value));},path};}return {data,doc:ref,collection:name=>({get:async()=>({docs:[]}),doc:id=>ref(name+'/'+id),where:()=>({get:async()=>({docs:[]})})}),runTransaction:async fn=>fn({get:r=>r.get(),set:(r,v,o)=>r.set(v,o)})};}
function setup(){const db=fakeDb();db.data.set('jddmEmailConfig/main',{enabled:true,tags:Object.fromEntries(Object.keys(STATES).map(k=>[k,k])),confirmationChannelId:'confirm'});const calls=[];let seq=0;const discord=async(method,path,body)=>{calls.push({method,path,body});return {id:'discord-'+(++seq)};};const modifications=[];const gmail={users:{threads:{modify:async x=>modifications.push(x)}}};const service=createConversationService({db,gmail,discord,now:()=>new Date('2026-09-07T15:00:00Z')});return {db,calls,gmail,service,modifications};}
test('all six requested colors and status choices are exposed',()=>{assert.equal(Object.keys(STATES).length,6);assert.deepEqual(Object.values(STATES).map(s=>s.emoji),['🟡','🔵','🟢','🔴','🟣','🟠']);assert.equal(controls('a')[1].components[0].options.length,6);});
test('calendar dates are validated and morning dates use Eastern time across DST',()=>{assert.equal(validDate('2026-02-30'),false);assert.equal(validDate('2028-02-29'),true);assert.equal(dateKey(new Date('2026-09-07T02:00:00Z')),'2026-09-06');assert.equal(dateKey(new Date('2026-12-01T04:30:00Z')),'2026-11-30');});
test('long email bodies are preserved in bounded ordered chunks',()=>{const body='This is the full booking discussion.\n'.repeat(300);const chunks=messageChunks(message('long',body));assert.ok(chunks.length>3);assert.ok(chunks.every(c=>c.content.length<=2000));assert.ok(chunks.every(c=>c.allowed_mentions.parse.length===0));assert.ok(chunks.at(-1).content.includes('booking discussion.'));assert.equal(new Set(chunks.map(c=>c.nonce)).size,chunks.length);});
test('quoted replies are removed but forwarded content is preserved',()=>{const reply=message('r','New answer\nOn Sunday Venue wrote:\nOld quoted history');assert.equal(plainBody(reply.payload),'New answer');const fwd=message('f','Please read\n---------- Forwarded message ---------\nImportant long content');assert.match(plainBody(fwd.payload),/Important long content/);});
test('two Gmail messages and a later response stay in one forum post with no duplicate delivery',async()=>{const s=setup();const first=message('one','Question');const second=message('two','Answer','justdeedeemusic@gmail.com',Date.now()+1);await s.service.syncThread({id:'gmail-thread',messages:[first,second]});await s.service.syncThread({id:'gmail-thread',messages:[first,second]});const incoming=message('three','Another question','venue@example.com',Date.now()+2);await s.service.syncThread({id:'gmail-thread',messages:[first,second,incoming]});assert.equal(s.calls.filter(c=>c.method==='POST'&&c.path.endsWith('/threads')).length,1);assert.equal(s.calls.filter(c=>c.method==='POST'&&c.path.endsWith('/messages')).length,3);assert.equal((await s.service.get('gmail-thread')).status,'deedee');});
test('a partially posted long message resumes at its next chunk',async()=>{const s=setup();const long=message('long','long content '.repeat(800));const t={id:'gmail-thread',messages:[long]};await s.service.syncThread(t,{budget:2});const first=s.calls.filter(c=>c.method==='POST'&&c.path.endsWith('/messages'));assert.equal(first.length,2);await s.service.syncThread(t);const all=s.calls.filter(c=>c.method==='POST'&&c.path.endsWith('/messages'));assert.equal(all.length,messageChunks(long).length);assert.equal(new Set(all.map(x=>x.body.nonce)).size,all.length);});
test('follow-up dates produce confirmations on added or changed dates, not identical saves',async()=>{const s=setup();await s.service.syncThread({id:'gmail-thread',messages:[message('one','Question')]});await s.service.setStatus('gmail-thread','followup','Dee Dee','2026-09-20');await s.service.setStatus('gmail-thread','followup','Dee Dee','2026-09-22');await s.service.setStatus('gmail-thread','followup','Dee Dee','2026-09-22');const notes=s.calls.filter(c=>c.path==='/channels/confirm/messages');assert.equal(notes.length,2);assert.match(notes[0].body.content,/added/);assert.match(notes[1].body.content,/Previous: 2026-09-20/);await s.service.setStatus('gmail-thread','resolved','Dee Dee');assert.equal((await s.service.get('gmail-thread')).followUpDate,'');assert.equal(s.modifications[0].id,'gmail-thread');});
test('spam actions apply to the whole Gmail conversation',async()=>{const s=setup();await s.service.syncThread({id:'gmail-thread',messages:[message('one','Question')]});await s.service.setStatus('gmail-thread','spam','Dee Dee');assert.deepEqual(s.modifications[0].requestBody,{addLabelIds:['SPAM'],removeLabelIds:['INBOX','UNREAD']});});
test('following up an outgoing message addresses its venue recipient, not Dee Dee herself',async()=>{const s=setup();const m=message('one','Sent offer','justdeedeemusic@gmail.com');m.payload.headers.find(h=>h.name==='To').value='Venue <venue@example.com>';await s.service.syncThread({id:'gmail-thread',messages:[m]});s.gmail.users.threads.get=async()=>({data:{id:'gmail-thread',messages:[m]}});let sent;s.gmail.users.messages={send:async x=>{sent=x;return {data:{id:'sent'}};}};const result=await s.service.reply('gmail-thread','Following up','Dee Dee');assert.equal(result.to,'Venue <venue@example.com>');assert.equal(sent.requestBody.threadId,'gmail-thread');assert.match(Buffer.from(sent.requestBody.raw,'base64url').toString(),/To: Venue <venue@example.com>/);});
test('daily digest combines due email and map items, excludes closed/future places and sends once',async()=>{const s=setup();s.db.data.get('jddmEmailConfig/main').dailyChannelId='daily';const collection=s.db.collection;s.db.collection=name=>({...collection(name),get:async()=>({docs:[{data:()=>({status:'followup',subject:'Email due',followUpDate:'2026-09-07',discordThreadId:'post'})},{data:()=>({status:'followup',subject:'Future email',followUpDate:'2026-10-01'})}]})});const service=createConversationService({...s,now:()=>new Date('2026-09-07T12:00:00Z'),discord:async(method,path,body)=>{s.calls.push({method,path,body});return{};},fetchImpl:async()=>({ok:true,text:async()=> 'Place Name,Next Follow Up,Status\nDue venue,2026-09-06,Contacted\nFuture venue,2026-10-01,Contacted\nClosed venue,2026-09-06,Booked'})});assert.deepEqual(await service.daily(),{emails:1,venues:1});assert.deepEqual(await service.daily(),{duplicate:true});const note=s.calls[0].body.content;assert.match(note,/Email due/);assert.match(note,/Due venue/);assert.doesNotMatch(note,/Future venue|Closed venue|Future email/);await service.daily({test:true});assert.match(s.calls[1].body.content,/TEST/);assert.equal(s.calls.length,2);});
test('daily digest resumes after partial delivery without resending earlier parts',async()=>{const s=setup();s.db.data.get('jddmEmailConfig/main').dailyChannelId='daily';let fail=true;const calls=[];const service=createConversationService({...s,discord:async(method,path,body)=>{if(calls.length===1&&fail){fail=false;throw Error('temporary failure');}calls.push(body);return{};},fetchImpl:async()=>({ok:true,text:async()=> 'Place Name,Next Follow Up,Status\n'+Array.from({length:100},(_,i)=>`Venue ${i} ${'name '.repeat(5)},2026-09-01,Contacted`).join('\n')})});await assert.rejects(()=>service.daily({today:'2026-09-07'}),/temporary failure/);await service.daily({today:'2026-09-07'});assert.equal(new Set(calls.map(c=>c.nonce)).size,calls.length);assert.ok(calls.length>2);assert.equal(calls.filter(c=>c.content.includes('Venue 0 ')).length,1);});
test('incremental poll reads changed threads once and checkpoints a burst across runs',async()=>{const s=setup();s.db.data.set('jddmEmailConfig/checkpoint',{historyId:'100',pending:[]});s.gmail.users.getProfile=async()=>({data:{emailAddress:'justdeedeemusic@gmail.com',historyId:'200'}});let histories=0;s.gmail.users.history={list:async()=>({data:{history:histories++?[]:[{messagesAdded:Array.from({length:27},(_,i)=>({message:{threadId:'t'+i}}))}]}})};let reads=0;s.gmail.users.threads.get=async({id})=>{reads++;return{data:{id,messages:[{...message('m'+id,'Hi'),threadId:id}]}};};const first=await s.service.poll();assert.equal(first.conversations,25);assert.equal(first.queued,2);const next=await s.service.poll();assert.equal(next.conversations,2);assert.equal(next.queued,0);await s.service.poll();assert.equal(reads,27);assert.equal(s.db.data.get('jddmEmailConfig/checkpoint').historyId,'200');});
function signedRequest(body){const crypto=require('node:crypto');const keys=crypto.generateKeyPairSync('ed25519');const der=keys.publicKey.export({type:'spki',format:'der'});const raw=JSON.stringify(body);const stamp=String(Math.floor(Date.now()/1000));const signature=crypto.sign(null,Buffer.from(stamp+raw),keys.privateKey).toString('hex');return {publicKey:der.subarray(-32).toString('hex'),req:{body,rawBody:Buffer.from(raw),get:n=>n==='X-Signature-Ed25519'?signature:stamp}};}
test('modal opens without waiting for database and effects acknowledge before database or Gmail',async()=>{const {createConversationInteractions,GUILD_ID}=require('../discordConversations');const s=setup();const order=[];const service={get:async()=>{order.push('lookup');return {discordThreadId:'post'};},setStatus:async()=>{order.push('effect');return {status:'resolved'};}};const call=async action=>{const {req,publicKey}=signedRequest({id:'interaction-'+action,token:'token',application_id:'app',guild_id:GUILD_ID,channel_id:'post',data:{custom_id:'jddm2:'+action+':gmail',values:['resolved']}});let json;const res={json:d=>{json=d;},status:()=>res,send:()=>{}};await createConversationInteractions({getConfig:()=>({publicKey}),service,db:s.db,discord:async(m,p,b)=>{order.push(b.type===5?'ack':'result');},legacy:()=>{}})(req,res);return json;};assert.equal((await call('reply')).type,9);assert.deepEqual(order,[]);await call('status');assert.deepEqual(order,['ack','lookup','effect','result']);});

test("spreadsheet date strings become readable calendar dates",()=>{const {followUpDate}=require("../discordConversations");assert.equal(followUpDate("Mon Sep 07 2026 00:00:00 GMT-0400 (Eastern Daylight Time)"),"2026-09-07");assert.equal(followUpDate("2026-02-30"),"");assert.equal(followUpDate(""),"");});

test("unsent drafts and trashed messages are not posted to Discord",async()=>{const s=setup();const a=message("draft","Unsent private draft");a.labelIds=["DRAFT"];const b=message("trash","Deleted message");b.labelIds=["TRASH"];await s.service.syncThread({id:"gmail-thread",messages:[a,b]});assert.equal(s.calls.length,0);});
test('Gig prep and Song requests labels survive the Gmail yellow-blue-yellow cycle',async()=>{const {TOPICS,summaryMessage,appliedTags}=require('../discordConversations');const s=setup();s.db.data.get('jddmEmailConfig/main').topicTags={gigprep:'teal',songs:'pink'};const outgoing=message('out','Here are the gig materials','justdeedeemusic@gmail.com',1000);outgoing.labelIds=['SENT'];await s.service.syncThread({id:'gmail-thread',messages:[outgoing]});await s.service.setTopics('gmail-thread',['gigprep','songs'],'Dee Dee');const incoming=message('in','Please add our song request','venue@example.com',2000);await s.service.syncThread({id:'gmail-thread',messages:[outgoing,incoming]});let c=await s.service.get('gmail-thread');assert.equal(c.status,'deedee');assert.deepEqual(c.topics,['gigprep','songs']);const second=message('out2','All set','justdeedeemusic@gmail.com',3000);second.labelIds=['SENT'];await s.service.syncThread({id:'gmail-thread',messages:[outgoing,incoming,second]});c=await s.service.get('gmail-thread');assert.equal(c.status,'venue');assert.deepEqual(appliedTags(c,await s.service.config()),['venue','teal','pink']);assert.deepEqual(summaryMessage(c).embeds.slice(1).map(e=>e.color),[TOPICS.gigprep.color,TOPICS.songs.color]);assert.equal(s.calls.filter(x=>x.method==='POST'&&x.path.endsWith('/threads')).length,1);});
test('sending a Gmail draft is discovered through its SENT label event',async()=>{const s=setup();s.db.data.set('jddmEmailConfig/checkpoint',{historyId:'100',pending:[]});s.gmail.users.getProfile=async()=>({data:{emailAddress:'justdeedeemusic@gmail.com',historyId:'200'}});s.gmail.users.history={list:async()=>({data:{history:[{labelsAdded:[{labelIds:['SENT'],message:{id:'sent',threadId:'gmail-thread'}}]}]}})};const m=message('sent','Sent directly from Gmail');m.labelIds=['SENT'];s.gmail.users.threads.get=async()=>({data:{id:'gmail-thread',messages:[m]}});assert.equal((await s.service.poll()).posted,1);assert.equal((await s.service.get('gmail-thread')).status,'venue');});
test('tidy post titles identify the correspondent and previews avoid technical email IDs',()=>{const {threadTitle,summaryMessage}=require('../discordConversations');const c={gmailThreadId:'id',subject:'Re: Re: Booking for October',correspondent:'"Venue Owner" <owner@example.com>',status:'venue',preview:'We sent the gig materials.'};assert.equal(threadTitle(c),'Venue Owner · Booking for October');assert.match(summaryMessage(c).content,/gig materials/);assert.doesNotMatch(summaryMessage(c).embeds[0].footer.text,/Gmail id/);assert.ok(messageChunks(message('id','Short email'))[0].content.endsWith('Short email'));});

test("wrapped Gmail reply headers do not repeat the earlier conversation",()=>{const m=message("wrapped","Testing 1,2,3!!\n\nCarter Swarm\n\nOn Mon, Sep 7, 2026 at 12:32 AM JustDeeDeeMusic <justdeedeemusic@gmail.com>\nwrote:\n\n> Test\n>");assert.equal(plainBody(m.payload),"Testing 1,2,3!!\n\nCarter Swarm");});

test("quotes inside forwarded material are preserved",()=>{const m=message("fwd","Please review\nBegin forwarded message:\nNew information\nOn Monday Venue wrote:\nEarlier material belonging to the forwarded email");assert.match(plainBody(m.payload),/Earlier material belonging to the forwarded email/);});

test('notification labels match subjects, including replies, not incidental body text',()=>{
 const {automaticTopics,TOPICS}=require('../discordConversations');
 const subject=(value)=>{const m=message(value,'New text message in quoted text');m.payload.headers.find(h=>h.name==='Subject').value=value;return m;};
 assert.deepEqual(automaticTopics([subject('RE: Fwd: New text message from venue'),subject('new EVENT: Gig')]),['textmessage','newevent']);
 assert.deepEqual(automaticTopics([subject('Booking'),subject('Renew event'),subject('New eventful season')]),[]);
 assert.notEqual(TOPICS.textmessage.color,TOPICS.newevent.color);
 assert.equal(controls('a')[2].components[0].max_values,4);
});
test('automatic labels persist with manual topics and apply to already imported conversations without reposting',async()=>{
 const s=setup();s.db.data.get('jddmEmailConfig/main').topicTags={textmessage:'brown',newevent:'white',gigprep:'teal',songs:'pink'};
 const m=message('one','Hello');m.payload.headers.find(h=>h.name==='Subject').value='New text message from venue';
 await s.service.syncThread({id:'gmail-thread',messages:[m]});
 assert.deepEqual((await s.service.get('gmail-thread')).topics,['textmessage']);
 await s.service.setTopics('gmail-thread',['gigprep','songs'],'Dee Dee');
 await s.service.setStatus('gmail-thread','followup','Dee Dee','2026-09-20');
 const before=s.calls.filter(c=>c.method==='POST'&&c.path.endsWith('/messages')).length;
 const result=await s.service.syncThread({id:'gmail-thread',messages:[m]});
 const c=await s.service.get('gmail-thread');assert.equal(result.posted,0);assert.equal(c.status,'followup');assert.equal(c.followUpDate,'2026-09-20');assert.deepEqual(c.topics,['gigprep','songs','textmessage']);
 assert.equal(s.calls.filter(c=>c.method==='POST'&&c.path.endsWith('/messages')).length,before);assert.equal(s.modifications.length,0);
 const event=message('two','Gig details',undefined,Date.now()+10);event.payload.headers.find(h=>h.name==='Subject').value='New Event: Music';
 await s.service.syncThread({id:'gmail-thread',messages:[m,event]});
 const {appliedTags}=require('../discordConversations');assert.equal(appliedTags(await s.service.get('gmail-thread'),await s.service.config()).length,5);
});
