const test=require('node:test'),assert=require('node:assert/strict');
const voice=require('../googleVoice'),email=require('../discordConversations');
function message(id='m1',number='2166591146',time=1000){return {id,threadId:'gmail-'+id,internalDate:String(time),labelIds:['INBOX'],payload:{mimeType:'text/plain',headers:[{name:'From',value:`"Contact" <14406281508.1${number}.secret@txt.voice.google.com>`},{name:'Subject',value:'New text message from '+voice.displayPhone(number)}],body:{data:Buffer.from('<https://voice.google.com>\nHello @everyone\nTo respond to this text message, reply to this email or visit Google Voice.\nYOUR ACCOUNT <https://voice.google.com> HELP CENTER\nfooter').toString('base64url')}}};}
function setup(){const data=new Map([['jddmVoiceConfig/main',{enabled:true,forumId:'forum',tags:{deedee:'blue',venue:'yellow',resolved:'green'},topicTags:{textmessage:'brown',songs:'pink'}}]]);const ref=path=>({path,id:path.split('/').at(-1),get:async()=>({exists:data.has(path),data:()=>structuredClone(data.get(path))}),set:async(v,o)=>data.set(path,o?.merge?{...data.get(path),...structuredClone(v)}:structuredClone(v))});const db={doc:ref,collection:name=>({doc:id=>ref(name+'/'+id),get:async()=>({docs:[...data].filter(([k])=>k.startsWith(name+'/')).map(([k,v])=>({id:k.split('/')[1],data:()=>structuredClone(v)}))}),where:()=>({get:async()=>({docs:[...data].filter(([k,v])=>k.startsWith(name+'/')&&v.venueId).map(([k,v])=>({id:k.split('/')[1],data:()=>v}))})})}),runTransaction:async fn=>fn({get:r=>r.get(),set:(r,v,o)=>r.set(v,o)})};const calls=[];let n=0;const discord=async(method,path,body)=>{calls.push({method,path,body});return path.endsWith('/threads/active')?{threads:[]}:{id:'post'+(++n)};};const venues=[{id:'venue',name:'Test venue',date:'2026-09-20',city:'Ohio',phones:['2166591146']}];const venueDirectory={list:async()=>venues,get:async id=>{const v=venues.find(v=>v.id===id);if(!v)throw Error('missing');return v;},search:async()=>venues,setDate:async(id,date,expected)=>{assert.equal(expected,venues[0].date);venues[0].date=date;return venues[0];}};const gmail={users:{getProfile:async()=>({data:{emailAddress:email.MAILBOX}}),messages:{list:async()=>({data:{messages:[{id:'m2'},{id:'m1'}]}}),get:async({id})=>({data:message(id,undefined,id==='m1'?1000:2000)})}}};const service=voice.createService({db,gmail,discord,venueDirectory,now:()=>new Date('2026-09-07T16:00:00Z')});return {data,db,discord,calls,service,gmail,venues};}
test('only genuine incoming SMS notifications with consistent US identity qualify',()=>{const m=message();assert.equal(voice.parseText(m).phone,'2166591146');assert.equal(voice.parseText(m).body,'Hello @everyone');for(const label of ['DRAFT','TRASH','SENT'])assert.equal(voice.parseText({...m,labelIds:[label]}),null);const h=(from,subject)=>({...m,payload:{...m.payload,headers:[{name:'From',value:from},{name:'Subject',value:subject}]}});assert.equal(voice.parseText(h('fake@example.com','New text message from (216) 659-1146')),null);assert.equal(voice.parseText(h(m.payload.headers[0].value,'Missed call from (216) 659-1146')),null);assert.equal(voice.parseText(h(m.payload.headers[0].value,'New voicemail from (216) 659-1146')),null);assert.equal(voice.parseText(h(m.payload.headers[0].value,'New text message from (440) 458-1296')),null);assert.equal(voice.phone('+1 (216) 659-1146'),'2166591146');});
test('messages across Gmail threads group by phone; repeat imports do not duplicate or reset tags',async()=>{const s=setup();await s.service.syncMessage(message());await s.service.setTopics('2166591146',['songs'],'Dee Dee');await s.service.setStatus('2166591146','resolved','Dee Dee');await s.service.syncMessage(message());assert.equal((await s.service.get('2166591146')).status,'resolved');await s.service.syncMessage(message('m2',undefined,2000));const c=await s.service.get('2166591146');assert.equal(c.status,'deedee');assert.deepEqual(c.topics,['textmessage','songs']);assert.equal(c.venueId,'venue');assert.equal(s.calls.filter(c=>c.method==='POST'&&c.path.endsWith('/threads')).length,1);assert.equal(s.calls.filter(c=>c.method==='POST'&&c.path.endsWith('/messages')).length,2);assert.ok(s.calls.filter(c=>c.method==='POST'&&c.path.endsWith('/messages')).every(c=>c.body.flags===4096&&c.body.allowed_mentions.parse.length===0));});
test('different numbers stay separate and ambiguous saved phones are not auto-linked',async()=>{const s=setup();s.venues.push({...s.venues[0],id:'different'});await s.service.syncMessage(message());await s.service.syncMessage(message('other','4404581296'));assert.equal((await s.service.get('2166591146')).venueId,'');assert.equal(s.calls.filter(c=>c.path.endsWith('/threads')).length,2);});
test('partial delivery resumes and does not resend successful chunks',async()=>{const s=setup();const m=message();m.payload.body.data=Buffer.from('Long message '.repeat(900)).toString('base64url');let fail=true;const service=voice.createService({...s,discord:async(method,path,body)=>{if(path.endsWith('/messages')&&s.calls.filter(c=>c.path.endsWith('/messages')).length===1&&fail){fail=false;throw Error('temporary');}return s.discord(method,path,body);},venueDirectory:{list:async()=>[]}});await assert.rejects(()=>service.syncMessage(m),/temporary/);await service.syncMessage(m);const sent=s.calls.filter(c=>c.path.endsWith('/messages'));assert.equal(sent.length,voice.chunks(voice.parseText(m)).length);assert.equal(new Set(sent.map(c=>c.body.nonce)).size,sent.length);});
test('read-only source has no call or send controls; statuses never mutate Gmail',async()=>{const s=setup();await s.service.syncMessage(message());await s.service.setStatus('2166591146','spam','Dee Dee');await assert.rejects(()=>s.service.reply(),/does not send/);const body=voice.card(await s.service.get('2166591146'));assert.doesNotMatch(JSON.stringify(body.components),/jddm2:|:reply:|tel:/);assert.match(JSON.stringify(body.components),/jddmv:venue-search:/);});
test('official follow-up requires linked venue and rejects stale link context',async()=>{const s=setup();await s.service.syncMessage(message());await assert.rejects(()=>s.service.setStatus('2166591146','followup','Dee Dee','2026-09-23',{hash:'stale',date:'2026-09-20'}),/link changed/);const hash=require('crypto').createHash('sha256').update('venue').digest('hex').slice(0,8);await s.service.setStatus('2166591146','followup','Dee Dee','2026-09-23',{hash,date:'2026-09-20'});assert.equal((await s.service.get('2166591146')).followUpDate,'2026-09-23');});
test('poll checkpoints oldest-first and repeat overlap does not repost',async()=>{const s=setup();assert.equal((await s.service.poll({limit:1})).pending,1);assert.equal((await s.service.poll()).more,false);assert.equal((await s.service.poll()).posted,0);assert.equal(s.calls.filter(c=>c.path.endsWith('/messages')&&c.method==='POST').length,2);});
test('email intake can exclude Google Voice while keeping unrelated email',async()=>{const s=setup();const svc=email.createConversationService({...s,excludeMessage:m=>!!voice.parseText(m)});assert.equal((await svc.syncThread({id:'thread',messages:[message()]})).posted,0);assert.equal(s.calls.length,0);});
test('calls and voicemail have separate phone identities and no call-back controls',()=>{const m=message();m.payload.headers=[{name:'From',value:'Google Voice <voice-noreply@google.com>'},{name:'Subject',value:'New missed call from (216) 659-1146.'}];m.payload.body.data=Buffer.from('<https://voice.google.com>\nMissed call\ncall back\n<https://voice.google.com/calls?a=nc,123>\nYOUR ACCOUNT <https://voice.google.com> footer').toString('base64url');const call=voice.parseRecord(m);assert.equal(call.kind,'calls');assert.equal(call.key,'calls-2166591146');assert.doesNotMatch(call.body,/call back|a=nc/);m.payload.headers[1].value='New voicemail from (216) 659-1146';const vm=voice.parseRecord(m);assert.equal(vm.key,'voicemail-2166591146');assert.notEqual(vm.key,call.key);m.payload.headers[1].value='New voicemail from Unknown';assert.equal(voice.parseRecord(m).phone,'');assert.match(voice.parseRecord(m).key,/unknown-m1/);});
test('text, missed call and voicemail from one number use three different forums',async()=>{const s=setup();s.data.get('jddmVoiceConfig/main').channels={text:{forumId:'texts'},calls:{forumId:'calls'},voicemail:{forumId:'voicemails'}};const a=message('text'),b=message('call'),c=message('voicemail');b.payload.headers=[{name:'From',value:'voice-noreply@google.com'},{name:'Subject',value:'New missed call from (216) 659-1146.'}];c.payload.headers=[{name:'From',value:'voice-noreply@google.com'},{name:'Subject',value:'New voicemail from (216) 659-1146'}];for(const m of [a,b,c])await s.service.syncMessage(m);assert.deepEqual(s.calls.filter(c=>c.method==='POST'&&c.path.endsWith('/threads')).map(c=>c.path),['/channels/texts/threads','/channels/calls/threads','/channels/voicemails/threads']);});
test('Voice interactions keep their own prefix and reject send actions before effects',async()=>{const crypto=require('node:crypto');const keys=crypto.generateKeyPairSync('ed25519'),publicKey=keys.publicKey.export({type:'spki',format:'der'}).subarray(-32).toString('hex');async function run(action){const body={type:3,guild_id:email.GUILD_ID,data:{custom_id:'jddmv:'+action+':2166591146'}};const raw=Buffer.from(JSON.stringify(body)),stamp=String(Math.floor(Date.now()/1000)),signature=crypto.sign(null,Buffer.concat([Buffer.from(stamp),raw]),keys.privateKey).toString('hex');let result;await email.createConversationInteractions({getConfig:()=>({publicKey}),prefix:'jddmv',readOnlySource:true,service:{},db:{},discord:()=>{throw Error('Unexpected side effect');},legacy:()=>{throw Error('Wrong routing');}})({body,rawBody:raw,get:k=>k==='X-Signature-Ed25519'?signature:stamp},{json:x=>{result=x;}});return result;}assert.equal((await run('reply')).type,4);const modal=await run('venue-query');assert.equal(modal.type,9);assert.match(modal.data.custom_id,/^jddmv:venue-search-submit:/);});
test('new messages do not repeatedly rename an unchanged phone thread',async()=>{const s=setup();const discord=async(method,path,body)=>{if(method==='GET'&&/^\/channels\/[^/]+$/.test(path)){const c=await s.service.get('2166591146');if(c)return {id:c.discordThreadId,name:voice.title(c),applied_tags:email.appliedTags(c,await s.service.config()),thread_metadata:{archived:false}};}return s.discord(method,path,body);};const service=voice.createService({...s,discord});await service.syncMessage(message());const before=s.calls.length;await service.syncMessage(message('later',undefined,2000));assert.equal(s.calls.slice(before).filter(x=>x.method==='PATCH'&&x.body?.name).length,0);});

test('voice rematches after a directory edit, preserves explicit unlink, and handles a directory outage',async()=>{
 const s=setup();await s.service.syncMessage(message('m1','4405551234'));assert.equal((await s.service.get('4405551234')).venueId,'');
 s.venues[0].phones.push('4405551234');await s.service.rematchUnlinked();assert.equal((await s.service.get('4405551234')).venueId,'venue');
 await s.service.linkVenue('4405551234','','Dee Dee','venue');await s.service.rematchUnlinked();assert.equal((await s.service.get('4405551234')).venueId,'');
 const c={phone:'4405551234',venueLinkMode:''};s.venues.push({...s.venues[0],id:'two'});assert.equal((await s.service.tryAutoLink(c)).venueId,undefined);
});
