'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('crypto'),R=require('../linkingReview');
function setup(){const data=new Map(),calls=[],links=[];let time=1000;const ref=path=>({path,get:async()=>({data:()=>structuredClone(data.get(path))}),set:async(v,o)=>data.set(path,o?.merge?{...data.get(path),...structuredClone(v)}:structuredClone(v))});const db={doc:ref,collection:n=>({get:async()=>({docs:[...data].filter(([p])=>p.startsWith(n+'/')).map(([p,v])=>({id:p.split('/')[1],data:()=>structuredClone(v)}))})}),runTransaction:async fn=>fn({get:r=>r.get(),set:(r,v,o)=>r.set(v,o)})};
 const index=[{id:'filia',name:'Filia Cellars',city:'Wadsworth, OH',linkable:true,search:'filia cellars wadsworth oh',date:'2026-09-20'},{id:'patina',name:'Patina Porch',city:'Cleveland',search:'patina porch cleveland',linkable:true,date:''}],directory={list:async()=>index,get:async id=>{const v=index.find(v=>v.id===id);if(!v)throw Error('Missing venue');return v;}};
 const services=Object.fromEntries(['email','voice','messenger','instagram'].map(source=>[source,{linkVenue:async(...args)=>links.push({source,args})}]));const calendarRows=[],calendar={list:async()=>calendarRows,choose:async(...args)=>links.push({source:'calendar',args}),reopen:async()=>{}};
 const discord=async(method,path,body)=>{calls.push({method,path,body});return {id:path.includes('/messages/')?path.split('/').at(-1):'message-'+calls.length};};const service=R.createService({db,discord,directory,services,calendar,now:()=>time++});return {db,data,index,calls,links,calendarRows,discord,service};}
const input={source:'email',sourceId:'thread',name:'Booking',correspondent:'Owner <owner@example.com>',sourceUrl:'https://discord.com/channels/1543777084265070623/source',venueId:'',candidates:['filia']};
const chooseValue=id=>crypto.createHash('sha256').update(id).digest('hex').slice(0,24);
test('card keeps dropdown, popup search, Add in app, Ignore and source together without notifications',async()=>{const s=setup(),r=await s.service.upsert(input,s.index),card=R.card(r);assert.equal(card.components[0].components[0].type,3);assert.deepEqual(card.components[1].components.map(c=>c.label),['Search venues','Add in app','Ignore','Open source']);assert.equal(card.flags,4096);assert.deepEqual(card.allowed_mentions,{parse:[]});assert.ok(card.components[1].components[1].url.includes('#linkingReview='));assert.doesNotMatch(JSON.stringify(card),/Confirm new row/);});
test('search changes the original card, tolerates typos and never creates a second message',async()=>{const s=setup(),r=await s.service.upsert(input,s.index);await s.service.act(r.id,'query','Filia Celars','', 'u',r.messageId);const n=await s.service.get(r.id);assert.equal(n.options.length,1);assert.equal(n.options[0].id,'filia');assert.equal(s.calls.filter(x=>x.method==='POST').length,1);assert.equal(s.calls.at(-1).path,'/channels/'+R.CHANNEL+'/messages/'+r.messageId);assert.equal(s.links.length,0);});
test('selection binds source card and choice version, updates the correct source and shows official date',async()=>{const s=setup(),r=await s.service.upsert(input,s.index);await assert.rejects(s.service.act(r.id,'select',chooseValue('filia'),99,'u',r.messageId),/choices changed/);await assert.rejects(s.service.act(r.id,'select',chooseValue('filia'),r.selectionVersion,'u','other'),/no longer current/);await s.service.act(r.id,'select',chooseValue('filia'),r.selectionVersion,'u',r.messageId);const n=await s.service.get(r.id);assert.equal(n.status,'linked');assert.equal(n.followUpDate,'2026-09-20');assert.deepEqual(s.links[0],{source:'email',args:['thread','filia','u','']});assert.match(R.card(n).content,/Linked/);});
test('ignore and reopen only change review state, repeat polling does not revive ignored messages',async()=>{const s=setup(),r=await s.service.upsert(input,s.index);await s.service.act(r.id,'ignore','',r.revision,'u',r.messageId);await s.service.upsert({...input,observedAt:9999},s.index);let n=await s.service.get(r.id);assert.equal(n.status,'ignored');assert.equal(s.links.length,0);await s.service.act(r.id,'reopen','',n.revision,'u',r.messageId);assert.equal((await s.service.get(r.id)).status,'pending');});
test('all incoming sources and existing calendar cards share the queue; known and test conversations do not add noise',async()=>{const s=setup();for(const [source,ns] of Object.entries(R.NS))s.data.set(ns+'Conversations/a',{subject:'Unknown',name:'Someone',discordThreadId:source});s.data.set('jddmEmailConversations/linked',{venueId:'filia'});s.data.set('jddmMessengerConversations/test',{testConversation:true});s.calendarRows.push({id:'cal',name:'Calendar venue',status:'pending',messageId:'existing-cal',active:true});await s.service.sync();assert.equal([...s.data.keys()].filter(p=>p.startsWith('jddmLinkingReviews/')).length,5);assert.ok(s.calls.some(x=>x.path.endsWith('/existing-cal')&&x.method==='PATCH'));assert.equal(s.calls.filter(x=>x.method==='POST').length,4);});
test('app draft is token scoped, preserves fragmented info, and does not create a row',async()=>{const s=setup(),r=await s.service.upsert({...input,source:'voice',phone:'4405551234'},s.index);await assert.rejects(s.service.draft(r.id,'wrong'),/invalid/);const d=await s.service.draft(r.id,r.draftToken);assert.equal(d.rawFields['Phone Number'],'4405551234');assert.equal(d.rawFields['Email/Contact'],'');assert.equal(d.rawFields['Place Name'],'');assert.equal(d.placeId,'linking-review-'+r.id);assert.equal(s.links.length,0);});
test('place explicitly saved in app links back on refresh, while repeated opening edits the same row',async()=>{const s=setup(),r=await s.service.upsert(input,s.index);s.index.push({id:r.draftPlaceId,name:'New venue',date:'',linkable:true});await s.service.upsert(input,s.index);assert.equal((await s.service.get(r.id)).status,'linked');assert.equal(s.links.length,1);assert.equal((await s.service.draft(r.id,r.draftToken)).existingId,r.draftPlaceId);});
test('long venue identifiers use bounded dropdown values',async()=>{const s=setup();s.index[0].id='long'.repeat(70);const r=await s.service.upsert(input,s.index);assert.ok(R.card(r).components[0].components[0].options.every(x=>x.value.length<=100));});
test('signed popup submissions acknowledge by updating the original card instead of sending bottom replies',async()=>{const s=setup(),r=await s.service.upsert(input,s.index),keys=crypto.generateKeyPairSync('ed25519'),pub=keys.publicKey.export({type:'spki',format:'der'}).subarray(-32).toString('hex');const handler=R.interactions({service:s.service,discord:s.discord,publicKey:()=>pub});async function invoke(action,extra={}){const body={type:action==='query'?5:3,id:'interaction',token:'test',guild_id:R.GUILD,channel_id:R.CHANNEL,member:{user:{id:'u'}},message:{id:r.messageId},data:{custom_id:`jddmlink:${action}:${r.id}`,components:[{components:[{custom_id:'query',value:'Filia Celars'}]}]},...extra};const raw=Buffer.from(JSON.stringify(body)),stamp=String(Math.floor(Date.now()/1000)),sig=crypto.sign(null,Buffer.concat([Buffer.from(stamp),raw]),keys.privateKey).toString('hex'),res={json(v){this.body=v;return this;},status(n){this.code=n;return this;},send(){return this;}};await handler({body,rawBody:raw,get:n=>n==='X-Signature-Ed25519'?sig:stamp},res);return res;}
 assert.equal((await invoke('search')).body.type,9);await invoke('query');assert.equal(s.calls.find(x=>x.path.includes('/callback')).body.type,6);assert.equal(s.calls.filter(x=>x.method==='POST'&&x.path.endsWith('/messages')).length,1);assert.equal((await invoke('search',{channel_id:'elsewhere'})).code,403);
});
