'use strict';
const {test}=require('node:test'), assert=require('node:assert/strict'), crypto=require('node:crypto');
const R=require('../messengerReplies'), M=require('../messengerInbox');
function setup(platform='messenger') {
 const data=new Map(),calls=[],copies=[];let time=Date.parse('2026-09-07T20:00:00Z'),sendError=null,copyError=false;
 const ref=path=>({get:async()=>({data:()=>data.get(path)}),set:async(v,o)=>data.set(path,o?.merge?{...data.get(path),...v}:v)});
 const db={doc:ref,runTransaction:async fn=>fn({get:r=>r.get(),set:(r,v,o)=>r.set(v,o)})};
 const c={id:platform==='instagram'?'a'.repeat(32):'t_123',sourceId:'source-123',platform,psid:'customer',name:'Carter',discordThreadId:'discord-post'};
 const thread={id:c.sourceId,participants:{data:[{id:M.PLATFORMS[platform].selfId},{id:'customer',name:'Carter'}]}};
 const recent=[{id:'incoming',from:{id:'customer'},created_time:new Date(time-10000).toISOString(),message:'Test request'}];
 const inbox={get:async id=>id===c.id?c:null,syncConversation:async t=>{if(copyError)throw Error('Discord down');copies.push(t);}};
 const transport=async(path,body)=>{calls.push({path,body});if(body){if(sendError)throw sendError;return {message_id:'sent-1'};}if(path==='me?fields=id,name')return {id:M.PAGE_ID};if(path.includes('instagram_business_account'))return {instagram_business_account:{id:M.INSTAGRAM_ID}};if(path.includes('/messages?'))return {data:recent};return thread;};
 const inboxes={[platform]:inbox},service=R.createService({db,transport,inboxes,now:()=>time});
 const send=(extra={})=>service.send({platform,id:c.id,channelId:c.discordThreadId,actionId:'action-1',text:'Hello Carter!',actor:'Dee Dee',...extra});
 return {data,db,c,calls,copies,thread,recent,inboxes,service,send,advance:ms=>time+=ms,failSend:e=>sendError=e,failCopy:()=>copyError=true};
}
test('Facebook reply verifies Page and recipient, sends once, and copies Meta ID into same source thread',async()=>{const s=setup(),r=await s.send();assert.equal(r.sent,true);const post=s.calls.find(c=>c.body);assert.equal(post.path,M.PAGE_ID+'/messages');assert.deepEqual(post.body,{recipient:{id:'customer'},message:{text:'Hello Carter!'},messaging_type:'RESPONSE'});assert.equal(s.copies[0].id,s.c.sourceId);assert.equal(s.copies[0].messages.at(-1).id,'sent-1');assert.equal(s.copies[0].messages[0].id,'incoming');assert.equal((await s.send()).duplicate,true);assert.equal(s.calls.filter(c=>c.body).length,1);});
test('Instagram verifies linked account, addresses its scoped contact, and uses Instagram sender identity',async()=>{const s=setup('instagram');await s.send();assert.ok(s.calls.some(c=>c.path.includes('instagram_business_account')));assert.equal(s.calls.find(c=>c.body).body.messaging_type,undefined);assert.equal(s.copies[0].messages.at(-1).from.id,M.INSTAGRAM_ID);assert.equal(R.compose('instagram',s.c.id).data.components[0].components[0].max_length,1000);});
test('wrong Discord post, source recipient, or source ownership never sends',async()=>{const s=setup();await assert.rejects(s.send({channelId:'other'}),/original conversation/);s.thread.participants.data[1].id='different';await assert.rejects(s.send(),/recipient/);s.thread.participants.data=[{id:'other-page'},{id:'customer'}];await assert.rejects(s.send(),/recipient/);assert.equal(s.calls.filter(c=>c.body).length,0);});
test('24-hour window uses incoming messages, not recent outgoing messages',async()=>{const s=setup();s.advance(24*60*60*1000);s.recent.push({id:'recent-outgoing',from:{id:M.PAGE_ID},created_time:'2026-09-08T19:59:59Z'});await assert.rejects(s.send(),/24-hour/);assert.equal(s.calls.filter(c=>c.body).length,0);});
test('identical text in a new interaction is blocked after sending',async()=>{const s=setup();await s.send();await assert.rejects(s.send({actionId:'action-2'}),/same reply/);assert.equal(s.calls.filter(c=>c.body).length,1);});
test('uncertain network send blocks duplicate text and repeated actions',async()=>{const s=setup();s.failSend(Object.assign(Error('No confirmation'),{uncertain:true}));await assert.rejects(s.send(),/confirmation/);s.failSend(null);s.advance(600000);await assert.rejects(s.send({actionId:'action-2'}),/same reply/);await assert.rejects(s.send(),/already attempted/);assert.equal(s.calls.filter(c=>c.body).length,1);});
test('definite Meta rejection can be corrected and submitted as a new action',async()=>{const s=setup();s.failSend(Error('Meta 200: denied'));await assert.rejects(s.send(),/denied/);s.failSend(null);assert.equal((await s.send({actionId:'new-action'})).sent,true);});
test('Discord copy failure is reported as sent, never as permission to resend',async()=>{const s=setup();s.failCopy();const r=await s.send();assert.equal(r.sent,true);assert.equal(r.syncPending,true);assert.equal((await s.send()).duplicate,true);assert.equal(s.calls.filter(c=>c.body).length,1);});
test('empty and oversized replies never reach Meta',async()=>{const s=setup('instagram');await assert.rejects(s.send({text:''}),/1,000/);await assert.rejects(s.send({text:'💛'.repeat(300)}),/1,000/);assert.equal(s.calls.length,0);});
test('send transport does not retry ambiguous requests or leak credentials',async()=>{let calls=0;const send=R.createTransport('private-test-token',async()=>{calls++;throw Error('network');});await assert.rejects(send('page/messages',{message:{text:'Hello'}}),e=>e.uncertain&&!e.message.includes('private-test-token'));assert.equal(calls,1);const fail=R.createTransport('token',async()=>({ok:false,status:403,json:async()=>({error:{code:200,message:'Denied'}})}));await assert.rejects(fail('page/messages',{}),e=>!e.uncertain&&/Denied/.test(e.message));});
test('Discord signed modal submission routes to social send; unsigned requests are rejected',async()=>{const s=setup(),keys=crypto.generateKeyPairSync('ed25519'),pub=keys.publicKey.export({type:'spki',format:'der'}).subarray(-32).toString('hex'),calls=[];const h=R.interactions({publicKey:()=>pub,service:s.service,inboxes:s.inboxes,discord:async(...args)=>calls.push(args)});async function invoke(action,valid=true){const body={type:action==='reply'?3:5,id:'interaction',token:'opaque',application_id:'app',guild_id:'1543777084265070623',channel_id:s.c.discordThreadId,member:{user:{id:'user'}},data:{custom_id:`jddms:${action}:messenger:${s.c.id}`,components:[{components:[{custom_id:'message',value:'Discord test reply'}]}]}};const raw=Buffer.from(JSON.stringify(body)),stamp=String(Math.floor(Date.now()/1000)),sig=crypto.sign(null,Buffer.concat([Buffer.from(stamp),raw]),keys.privateKey).toString('hex');const res={json(v){this.body=v;return this;},status(n){this.code=n;return this;},send(){return this;}};await h({body,rawBody:raw,get:k=>k==='X-Signature-Ed25519'?(valid?sig:'bad'):stamp},res);return res;}
 assert.equal((await invoke('reply')).body.type,9);assert.equal((await invoke('send',false)).code,401);await invoke('send');assert.equal(s.calls.filter(c=>c.body).length,1);assert.equal(calls[0][2].type,5);assert.match(calls.at(-1)[2].content,/Sent as Just Dee Dee Music via Messenger/);});
