'use strict';
const {test,after}=require('node:test'),assert=require('node:assert/strict');
const {Firestore,FieldValue,FieldPath}=require('@google-cloud/firestore');
const S=require('../operationStore');
const run=process.env.FIRESTORE_EMULATOR_HOST?test:test.skip;
const raw=new Firestore({projectId:'demo-jddm-efficiency'}),db=S.operationDb(raw),name='jddmBooking2027Venues';
async function reset(){await fetch('http://'+process.env.FIRESTORE_EMULATOR_HOST+'/emulator/v1/projects/demo-jddm-efficiency/databases/(default)/documents',{method:'DELETE'});await raw.doc(S.CONTROL).set({enabled:true});}
after(()=>raw.terminate());
run('collection snapshot preserves complete records and reduces 250 reads to one',async()=>{await reset();const b=raw.batch();for(let i=0;i<250;i++)b.set(raw.doc(name+'/'+i),{id:String(i),n:i,map:{a:'full text',b:['x',true,null]}});await b.commit();const source=await raw.collection(name).get();assert.deepEqual((await db.collection(name).get()).docs.map(d=>d.data()),source.docs.map(d=>d.data()));await S.measured('test-hit',async()=>{await db.collection(name).get();await db.collection(name).get();const metrics=S.context.getStore().collections;assert.equal(metrics[S.CACHE].documentReads,2);assert.equal(metrics[name].documentReads,undefined);assert.equal(metrics[name].recordsDelivered,500);});});
run('canonical and materialized set, merge, update, delete and batch agree',async()=>{await reset();await db.collection(name).get();const ref=db.doc(name+'/record');await ref.set({a:1,nested:{x:1,y:2},keep:true});await ref.set({nested:{x:3}},{merge:true});await ref.update({'nested.y':4});await db.runTransaction(async tx=>{assert.equal((await tx.get(ref)).data().a,1);tx.update(ref,{a:2});tx.set(ref,{extra:'value'},{merge:true});});assert.deepEqual((await db.collection(name).get()).docs[0].data(),(await raw.doc(ref.path).get()).data());await db.batch().delete(ref).set(db.doc(name+'/new'),{ok:true}).commit();assert.deepEqual((await db.collection(name).get()).docs.map(d=>d.data()),[{ok:true}]);});
run('native transform and FieldPath operations invalidate without losing values',async()=>{await reset();await db.doc(name+'/x').set({count:1});await db.collection(name).get();await db.doc(name+'/x').update({count:FieldValue.increment(1)});assert.equal((await raw.doc(S.CACHE+'/'+name).get()).data().valid,false);assert.equal((await db.collection(name).get()).docs[0].data().count,2);await db.doc(name+'/x').update(new FieldPath('literal.dot'),4);assert.equal((await db.collection(name).get()).docs[0].data()['literal.dot'],4);await db.doc(name+'/x').set({at:FieldValue.serverTimestamp()},{merge:true});assert.equal(typeof (await db.collection(name).get()).docs[0].data().at.toMillis,'function');});
run('out-of-band repair checks current canonical state and never replays old event values',async()=>{await reset();await db.doc(name+'/x').set({version:1});await db.collection(name).get();await raw.doc(name+'/x').set({version:2});assert.deepEqual(await S.repair(db,name,'x'),{invalidated:true});assert.equal((await db.collection(name).get()).docs[0].data().version,2);await db.doc(name+'/x').set({version:3});assert.deepEqual(await S.repair(db,name,'x'),{unchanged:true});assert.equal((await db.collection(name).get()).docs[0].data().version,3);});
run('concurrent independent writes preserve both and failed transactions commit neither',async()=>{await reset();await db.collection(name).get();await Promise.all(Array.from({length:8},(_,i)=>db.doc(name+'/'+i).set({value:i})));assert.equal((await db.collection(name).get()).size,8);await assert.rejects(db.runTransaction(async tx=>{tx.set(db.doc(name+'/bad'),{bad:true});throw Error('abort');}),/abort/);assert.equal((await raw.doc(name+'/bad').get()).exists,false);assert.equal((await db.collection(name).get()).size,8);});
run('disabled, corrupted and oversized materializations use authoritative results',async()=>{await reset();await db.doc(name+'/x').set({value:1});await db.collection(name).get();await raw.doc(S.CACHE+'/'+name).set({schema:1,valid:true,packed:'broken',builtAt:Date.now()});assert.equal((await db.collection(name).get()).size,1);await raw.doc(S.CONTROL).set({enabled:false});await raw.doc(name+'/y').set({value:2});assert.equal((await db.collection(name).get()).size,2);assert.throws(()=>S.pack({large:require('crypto').randomBytes(700000).toString('base64')}),/safe size/);assert.throws(()=>S.operationDb({projectId:'barkrangermap-auth'}),/foreign/);});
run('a legacy write detected during an application transaction invalidates the entire snapshot',async()=>{await reset();await db.doc(name+'/x').set({value:1});await db.collection(name).get();await raw.doc(name+'/x').set({value:5});await db.doc(name+'/x').set({extra:true},{merge:true});assert.equal((await raw.doc(S.CACHE+'/'+name).get()).data().valid,false);assert.deepEqual((await db.collection(name).get()).docs[0].data(),{value:5,extra:true});});

run('type-changing merges and special field names preserve canonical data exactly',async()=>{await reset();const ref=db.doc(name+'/types');await ref.set({nested:'string',list:['array']});await db.collection(name).get();await ref.set({nested:{a:1},list:{b:2}},{merge:true});assert.deepEqual((await db.collection(name).get()).docs[0].data(),(await raw.doc(ref.path).get()).data());await assert.rejects(ref.set(JSON.parse('{"__proto__":{"safe":true}}'),{merge:true}),/reserved name/);assert.deepEqual((await db.collection(name).get()).docs[0].data(),(await raw.doc(ref.path).get()).data());assert.equal({}.safe,undefined);});
