'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {indexRows,searchVenues,matchVenue,createVenueDirectory}=require('../venueLinks');
const {createConversationService,createConversationInteractions,controls,GUILD_ID}=require('../discordConversations');
const {buildDigest}=require('../followUpDigest');
const row=(id,name,email,date='2026-09-20')=>({'Place ID':id,'Place Name':name,City:'Cleveland',State:'OH','Email/Contact':email,'Next Follow Up':date});
const msg=(email,id='m1',time=1)=>({id,internalDate:String(time),labelIds:['INBOX'],payload:{headers:[{name:'From',value:email},{name:'To',value:'justdeedeemusic@gmail.com'},{name:'Subject',value:'Booking'}],mimeType:'text/plain',body:{data:Buffer.from('Hello').toString('base64url')}}});
function fakeDb(){const data=new Map();const ref=path=>({path,get:async()=>({exists:data.has(path),data:()=>structuredClone(data.get(path))}),set:async(v,o)=>data.set(path,o?.merge?{...data.get(path),...structuredClone(v)}:structuredClone(v))});const docs=(name,filter=()=>true)=>[...data].filter(([k,v])=>k.startsWith(name+'/')&&filter(v)).map(([k])=>({id:k.split('/')[1],data:()=>structuredClone(data.get(k))}));return {data,doc:ref,collection:name=>({doc:id=>ref(name+'/'+id),get:async()=>({docs:docs(name)}),where:(field,op,value)=>({get:async()=>({docs:docs(name,v=>op==='>'?v[field]>value:v[field]===value)})})}),runTransaction:fn=>fn({get:r=>r.get(),set:(r,v,o)=>r.set(v,o)})};}
function setup(){const db=fakeDb(),calls=[],index=indexRows([row('a','Venue A','a@example.com'),row('b','Venue B','b@example.com')]);const writes=[];const directory={list:async()=>index,get:async id=>{const v=index.find(x=>x.id===id);if(!v)throw Error('missing venue');return v;},search:async q=>searchVenues(index,q),setDate:async(id,date,expected)=>{const v=index.find(x=>x.id===id);if(v.date!==expected)throw Error('changed');writes.push({id,date,expected});v.date=date;return v;}};const discord=async(method,path,body)=>{calls.push({method,path,body});return{id:'post',message:{id:'starter'}};};const service=createConversationService({db,discord,gmail:{users:{threads:{modify:async()=>{}}}},venueDirectory:directory,now:()=>new Date('2026-09-07T12:00:00Z')});return {db,calls,index,directory,discord,service,writes};}
test('exact addresses match incoming and outgoing mail; body and own address do not',()=>{const index=indexRows([row('a','Venue','A@Example.com')]);assert.equal(matchVenue(index,[msg('Owner <a@example.com>')]).venue.id,'a');const out=msg('justdeedeemusic@gmail.com');out.payload.headers[1].value='a@example.com';assert.equal(matchVenue(index,[out]).venue.id,'a');assert.equal(matchVenue(index,[msg('stranger@example.com')]).venue,null);});
test('shared addresses, multiple venues and duplicate IDs never guess a link',()=>{const index=indexRows([row('a','One','shared@example.com'),row('b','Two','shared@example.com')]);assert.equal(matchVenue(index,[msg('shared@example.com')]).venue,null);const multi=indexRows([row('a','One','a@example.com'),row('b','Two','b@example.com')]);assert.equal(matchVenue(multi,[msg('a@example.com'),msg('b@example.com')]).venue,null);const dupe=indexRows([row('a','One','a@example.com'),row('a','Two','b@example.com')]);assert.equal(matchVenue(dupe,[msg('a@example.com')]).venue,null);assert.equal(searchVenues(dupe,'One').length,0);});
test('search supports partial names, city and email without changing the sheet',()=>{const index=indexRows([row('a','Café Venue','owner@example.com')]);for(const q of ['cafe','cleveland','owner@example','cafe OH'])assert.equal(searchVenues(index,q)[0].id,'a');assert.deepEqual(searchVenues(index,'z'),[]);});
test('phone-only and email-only contacts can be searched independently',()=>{const r=row('a','Venue','');r['Booking Contact']='JDDM_CONTACTS_V2\n'+JSON.stringify({version:2,contacts:[{name:'Owner',notes:'',emails:[{value:'owner@example.com'}],phones:[],others:[]},{name:'Manager',notes:'',emails:[],phones:[{value:'(440) 555-1234'}],others:[]}]});const index=indexRows([r]);assert.equal(searchVenues(index,'Manager 440')[0].id,'a');assert.equal(searchVenues(index,'Owner')[0].id,'a');assert.equal(matchVenue(index,[msg('owner@example.com')]).venue.id,'a');});
test('automatic linking survives Gmail replies; a manual override or unlink stays fixed',async()=>{const s=setup();await s.service.syncThread({id:'thread',messages:[msg('a@example.com')]});let c=await s.service.get('thread');assert.equal(c.venueId,'a');assert.equal(c.followUpDate,'2026-09-20');await s.service.linkVenue('thread','b','Dee Dee','a');await s.service.syncThread({id:'thread',messages:[msg('a@example.com'),msg('a@example.com','m2',2)]});c=await s.service.get('thread');assert.equal(c.venueId,'b');assert.equal(c.followUpDate,'2026-09-20');await s.service.linkVenue('thread','','Dee Dee','b');await s.service.syncThread({id:'thread',messages:[msg('a@example.com'),msg('a@example.com','m3',3)]});assert.equal((await s.service.get('thread')).venueId,'');assert.equal(s.writes.length,0);});
test('linked date changes update the official venue and other threads while preserving waiting state',async()=>{const s=setup();await s.service.syncThread({id:'one',messages:[msg('a@example.com')]});await s.service.syncThread({id:'two',messages:[msg('a@example.com')]});const c=await s.service.get('one'),context=controls('one',[],c)[0].components[1].custom_id.split(':');await s.service.setStatus('one','followup','Dee Dee','2026-09-23',{date:context[3],hash:context[4]});assert.deepEqual(s.writes,[{id:'a',date:'2026-09-23',expected:'2026-09-20'}]);assert.equal((await s.service.get('two')).followUpDate,'2026-09-23');assert.equal((await s.service.get('one')).status,'deedee');await s.service.setStatus('one','resolved','Dee Dee');assert.equal((await s.service.get('one')).followUpDate,'2026-09-23');});
test('unlinked, stale date, stale venue and invalid dates cannot write the spreadsheet',async()=>{const s=setup();await s.service.syncThread({id:'thread',messages:[msg('unknown@example.com')]});await assert.rejects(s.service.setStatus('thread','followup','D','2026-09-23'),/Link this/);await s.service.linkVenue('thread','a','D','');await assert.rejects(s.service.setStatus('thread','followup','D','2026-09-23',{date:'2026-09-10'}),/changed/);await assert.rejects(s.service.setStatus('thread','followup','D','2026-09-23',{hash:'wrong'}),/linked venue changed/);await assert.rejects(s.service.setStatus('thread','followup','D','2026-02-30'),/Choose today/);await assert.rejects(s.service.linkVenue('thread','b','D',''),/linked venue changed/);assert.equal(s.writes.length,0);});
test('legacy date conflicts stay visible and are not automatically discarded',async()=>{const s=setup();s.db.data.set('jddmEmailConversations/thread',{gmailThreadId:'thread',subject:'Booking',discordThreadId:'post',followUpDate:'2026-09-21',status:'followup'});let c=await s.service.tryAutoLink(await s.service.get('thread'),[msg('a@example.com')]);assert.ok(!c.venueId);assert.match(c.venueLinkIssue,/differs/);c=await s.service.linkVenue('thread','a','D','');assert.equal(c.legacyFollowUpDate,'2026-09-21');assert.equal(c.followUpDate,'2026-09-20');assert.equal(s.writes.length,0);});
test('changes made in the map refresh linked cards without changing email status',async()=>{const s=setup();await s.service.syncThread({id:'thread',messages:[msg('a@example.com')]});s.index[0].date='2026-09-29';await s.service.refreshLinked();assert.equal((await s.service.get('thread')).followUpDate,'2026-09-29');assert.equal((await s.service.get('thread')).status,'deedee');});
test('busy venue actions reject before any venue date write',async()=>{const s=setup();await s.service.syncThread({id:'thread',messages:[msg('a@example.com')]});s.db.data.set('jddmVenueActionLocks/thread',{until:Date.now()+5000});await assert.rejects(s.service.setStatus('thread','followup','D','2026-09-29'),/still saving/);assert.equal(s.writes.length,0);});
test('daily reminders use the spreadsheet date once and include linked conversations',()=>{const result=buildDigest({today:'2026-09-20',rows:[row('a','Venue','a@example.com')],emails:[{venueId:'a',status:'followup',followUpDate:'2026-09-21',discordThreadId:'one'},{venueId:'a',status:'deedee',discordThreadId:'two'},{status:'followup',followUpDate:'2026-09-20',subject:'Unlinked legacy',discordThreadId:'three'}]});assert.equal(result.venues,1);assert.equal(result.emails,1);assert.match(result.body,/\/one/);assert.match(result.body,/\/two/);assert.match(result.body,/Unlinked legacy/);});
test('bridge writes only the existing date field with an optimistic comparison and verifies readback',async()=>{let date='2026-09-20',writes=[];const directory=createVenueDirectory({fetchImpl:async(url,opts)=>{if(opts.method==='POST'){const body=JSON.parse(opts.body);writes.push(body);date=body.rawFields['Next Follow Up'];return{ok:true,json:async()=>({ok:true})};}return{ok:true,text:async()=>`Place ID,Place Name,Next Follow Up\na,Venue,${date}`};}});await directory.setDate('a','2026-09-23','2026-09-20');assert.deepEqual(writes,[{action:'saveVenue',id:'a',rawFields:{'Next Follow Up':'2026-09-23'},expectedRawFields:{'Next Follow Up':'2026-09-20'}}]);await assert.rejects(directory.setDate('a','2026-09-24','2026-09-20'),/changed/);await assert.rejects(directory.setDate('missing','2026-09-24',''),/missing/);assert.equal(writes.length,1);});
async function interact(s,custom,extra={}){const keys=crypto.generateKeyPairSync('ed25519'),publicKey=keys.publicKey.export({type:'spki',format:'der'}).subarray(-32).toString('hex');const body={type:3,id:crypto.randomUUID(),token:'token',application_id:'app',guild_id:GUILD_ID,channel_id:'post',member:{user:{id:'user',username:'D'}},data:{custom_id:custom,...extra.data},...extra};const raw=JSON.stringify(body),stamp=String(Math.floor(Date.now()/1000)),signature=crypto.sign(null,Buffer.from(stamp+raw),keys.privateKey).toString('hex');let json;const res={json:v=>json=v,status:()=>res,send:()=>{}};await createConversationInteractions({getConfig:()=>({publicKey}),...s,legacy:()=>{}})({body,rawBody:Buffer.from(raw),get:n=>n==='X-Signature-Ed25519'?signature:stamp},res);return json||s.calls.at(-1).body;}
test('venue search opens immediately and returns a bounded private dropdown without an add-place option',async()=>{const s=setup();await s.service.syncThread({id:'thread',messages:[msg('a@example.com')]});const modal=await interact(s,'jddm2:venue-search:thread');assert.equal(modal.type,9);for(let i=0;i<30;i++)s.index.push({...s.index[0],id:'z'+i,name:'Venue '+i});const out=await interact(s,'jddm2:venue-search-submit:thread',{data:{custom_id:'jddm2:venue-search-submit:thread',components:[{components:[{custom_id:'value',value:'venue'}]}]}});assert.equal(out.components[0].components[0].options.length,25);assert.match(out.content,/first 24/);assert.ok(!out.components[0].components[0].options.some(o=>/add|create/i.test(o.label)));const session=s.db.data.get('jddmVenueSelections/'+out.components[0].components[0].custom_id.split(':')[3]);assert.equal(session.user,'user');assert.equal(session.offered.length,24);});
test('search selection is bound to user, conversation, offered IDs and expiration',async()=>{const s=setup();await s.service.syncThread({id:'thread',messages:[msg('a@example.com')]});const ref=s.db.doc('jddmVenueSelections/selection');const saved={conversationId:'thread',user:'user',venueId:'a',offered:['b'],expiresAt:Date.now()+60000};await ref.set(saved);const choose=extra=>interact(s,'jddm2:venue-select:thread:selection',{data:{custom_id:'jddm2:venue-select:thread:selection',values:['b']},...extra});assert.match((await choose({member:{user:{id:'someone'}}})).content,/another person/);assert.equal((await s.service.get('thread')).venueId,'a');assert.match((await choose({channel_id:'elsewhere'})).content,/current conversation/);assert.match((await choose({data:{custom_id:'jddm2:venue-select:thread:selection',values:['invented']}})).content,/these search results/);await ref.set({...saved,expiresAt:1});assert.match((await choose()).content,/expired/);await ref.set(saved);assert.match((await choose()).content,/Linked to/);assert.equal((await s.service.get('thread')).venueId,'b');assert.equal(s.writes.length,0);});
test('two conversations cannot concurrently write different dates to the same venue',async()=>{const s=setup();await s.service.syncThread({id:'one',messages:[msg('a@example.com')]});await s.service.syncThread({id:'two',messages:[msg('a@example.com')]});const key='jddmVenueActionLocks/place-'+crypto.createHash('sha256').update('a').digest('hex');s.db.data.set(key,{until:Date.now()+5000});await assert.rejects(s.service.setStatus('two','followup','D','2026-09-29'),/still saving/);assert.equal(s.writes.length,0);});
test('a venue-directory outage does not prevent new email delivery',async()=>{const s=setup();s.directory.list=async()=>{throw Error('offline');};const result=await s.service.syncThread({id:'one',messages:[msg('a@example.com')]});assert.equal(result.posted,1);const c=await s.service.get('one');assert.ok(!c.venueId);assert.match(c.venueLinkIssue,/temporarily unavailable/);});
